version: "2"
linters:
  default: none
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - Prefix(github.com/canonical/pebble)
  exclusions:
    generated: lax
issues:
  # these values ensure that all issues will be surfaced
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m

