// Code generated by cotorp. DO NOT EDIT.
// source: common/v1/common.proto

package v1

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	commonWireVarint                         = 0
	commonWireFixed64                        = 1
	commonWireBytes                          = 2
	commonWireStartGroup                     = 3
	commonWireEndGroup                       = 4
	commonWireFixed32                        = 5
	commonTagTypeBits                        = 3
	commonTagTypeMask                        = 1<<3 - 1
	commonMaxFieldNumber                     = 1<<29 - 1
	commonFixed32Size                        = 4
	commonFixed64Size                        = 8
	commonVarintPayloadBits                  = 7
	commonVarintContBit                      = 0x80
	commonMaxDepth                           = 10000
	commonSkipStackSize                      = 16
	commonClassNone                          = 0
	commonClassSigned                        = 1
	commonClassUnsigned                      = 2
	commonClassFloat                         = 3
	commonClassBool                          = 4
	commonClassString                        = 5
	commonClassBytes                         = 6
	commonMaxJSONExponent                    = 100
	commonBase64Quantum                      = 4
	commonAnyValueStringValueErrUTF8         = "proto: field opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8"
	commonErrDepth                           = "proto: exceeded maximum recursion depth"
	commonErrParse                           = "proto: cannot parse invalid wire-format data"
	commonKeyValueKeyErrUTF8                 = "proto: field opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8"
	commonInstrumentationScopeVersionErrUTF8 = "proto: field opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8"
	commonInstrumentationScopeNameErrUTF8    = "proto: field opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8"
	commonEntityRefDescriptionKeysErrUTF8    = "proto: field opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8"
	commonEntityRefIdKeysErrUTF8             = "proto: field opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8"
	commonEntityRefTypeErrUTF8               = "proto: field opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8"
	commonEntityRefSchemaUrlErrUTF8          = "proto: field opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8"
	commonErrInvalidInteger                  = "invalid integer "
	commonErrInvalidNumber                   = "invalid number "
)

// Represents any type of attribute value. AnyValue may contain a
// primitive value such as a string or integer or it may contain an arbitrary nested
// object containing arrays, key-value lists and primitives.
type AnyValue struct {
	// The value is one of the listed fields. It is valid for all values to be unspecified
	// in which case this AnyValue is considered to be "empty".
	//
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	//	*AnyValue_BytesValue
	//	*AnyValue_StringValueStrindex
	Value isAnyValue_Value

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *AnyValue) Reset() { *m = AnyValue{} }

func (m *AnyValue) GetValue() isAnyValue_Value {
	return commonGet(m, func(m *AnyValue) isAnyValue_Value { return m.Value })
}
func (m *AnyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*AnyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}
func (m *AnyValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*AnyValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}
func (m *AnyValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*AnyValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}
func (m *AnyValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*AnyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}
func (m *AnyValue) GetArrayValue() *ArrayValue {
	if x, ok := m.GetValue().(*AnyValue_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}
func (m *AnyValue) GetKvlistValue() *KeyValueList {
	if x, ok := m.GetValue().(*AnyValue_KvlistValue); ok {
		return x.KvlistValue
	}
	return nil
}
func (m *AnyValue) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*AnyValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}
func (m *AnyValue) GetStringValueStrindex() int32 {
	if x, ok := m.GetValue().(*AnyValue_StringValueStrindex); ok {
		return x.StringValueStrindex
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *AnyValue) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *AnyValue) []byte { return m.unknownFields })
}

type isAnyValue_Value interface{ isAnyValue_Value() }
type AnyValue_StringValue struct{ StringValue string }
type AnyValue_BoolValue struct{ BoolValue bool }
type AnyValue_IntValue struct{ IntValue int64 }
type AnyValue_DoubleValue struct{ DoubleValue float64 }
type AnyValue_ArrayValue struct{ ArrayValue *ArrayValue }
type AnyValue_KvlistValue struct{ KvlistValue *KeyValueList }
type AnyValue_BytesValue struct{ BytesValue []byte }

// Reference to the string value in ProfilesDictionary.string_table.
//
// Note: This is currently used exclusively in the Profiling signal.
// Implementers of OTLP receivers for signals other than Profiling should
// treat the presence of this value as a non-fatal issue.
// Log an error or warning indicating an unexpected field intended for the
// Profiling signal and process the data as if this value were absent or
// empty, ignoring its semantic content for the non-Profiling signal.
//
// Status: [Alpha]
type AnyValue_StringValueStrindex struct{ StringValueStrindex int32 }

func (*AnyValue_StringValue) isAnyValue_Value()         {}
func (*AnyValue_BoolValue) isAnyValue_Value()           {}
func (*AnyValue_IntValue) isAnyValue_Value()            {}
func (*AnyValue_DoubleValue) isAnyValue_Value()         {}
func (*AnyValue_ArrayValue) isAnyValue_Value()          {}
func (*AnyValue_KvlistValue) isAnyValue_Value()         {}
func (*AnyValue_BytesValue) isAnyValue_Value()          {}
func (*AnyValue_StringValueStrindex) isAnyValue_Value() {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *AnyValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	switch o := m.Value.(type) {
	case *AnyValue_StringValue:
		n += 1 + commonSizeLen(len(o.StringValue))
	case *AnyValue_BoolValue:
		n += 1 + 1
	case *AnyValue_IntValue:
		n += 1 + (bits.Len64(uint64(o.IntValue)|1)+commonVarintPayloadBits-1)/commonVarintPayloadBits
	case *AnyValue_DoubleValue:
		n += 1 + commonFixed64Size
	case *AnyValue_ArrayValue:
		n += 1 + commonSizeLen(o.ArrayValue.ProtoSize())
	case *AnyValue_KvlistValue:
		n += 1 + commonSizeLen(o.KvlistValue.ProtoSize())
	case *AnyValue_BytesValue:
		n += 1 + commonSizeLen(len(o.BytesValue))
	case *AnyValue_StringValueStrindex:
		n += 1 + (bits.Len64(uint64(int64(o.StringValueStrindex))|1)+commonVarintPayloadBits-1)/commonVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *AnyValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *AnyValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *AnyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		i = commonPutVarint(b, commonPutVarint(b, i, uint64(int64(o.StringValueStrindex))), 8<<commonTagTypeBits|commonWireVarint)
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(o.BytesValue):], o.BytesValue), uint64(len(o.BytesValue))), 7<<commonTagTypeBits|commonWireBytes)
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		n, err := o.KvlistValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 6<<commonTagTypeBits|commonWireBytes)
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		n, err := o.ArrayValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 5<<commonTagTypeBits|commonWireBytes)
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		i = commonPutVarint(b, commonPutFixed64(b, i, math.Float64bits(o.DoubleValue)), 4<<commonTagTypeBits|commonWireFixed64)
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		i = commonPutVarint(b, commonPutVarint(b, i, uint64(o.IntValue)), 3<<commonTagTypeBits|commonWireVarint)
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		i = commonPutVarint(b, commonPutBool(b, i, o.BoolValue), 2<<commonTagTypeBits|commonWireVarint)
	}
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		if !utf8.ValidString(o.StringValue) {
			return 0, errors.New(commonAnyValueStringValueErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(o.StringValue):], o.StringValue), uint64(len(o.StringValue))), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *AnyValue) UnmarshalBinary(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *AnyValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonAnyValueStringValueErrUTF8)
			}
			b, m.Value = b[n:], &AnyValue_StringValue{StringValue: string(x)}
		case 2<<commonTagTypeBits | commonWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b, m.Value = b[n:], &AnyValue_BoolValue{BoolValue: x != 0}
		case 3<<commonTagTypeBits | commonWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b, m.Value = b[n:], &AnyValue_IntValue{IntValue: int64(x)}
		case 4<<commonTagTypeBits | commonWireFixed64:
			if len(b) < commonFixed64Size {
				goto errParse
			}
			b, m.Value = b[commonFixed64Size:], &AnyValue_DoubleValue{DoubleValue: math.Float64frombits(binary.LittleEndian.Uint64(b))}
		case 5<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			var mv *ArrayValue
			if o, ok := m.Value.(*AnyValue_ArrayValue); ok && o.ArrayValue != nil {
				mv = o.ArrayValue
			} else {
				mv = &ArrayValue{}
				m.Value = &AnyValue_ArrayValue{ArrayValue: mv}
			}
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 6<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			var mv *KeyValueList
			if o, ok := m.Value.(*AnyValue_KvlistValue); ok && o.KvlistValue != nil {
				mv = o.KvlistValue
			} else {
				mv = &KeyValueList{}
				m.Value = &AnyValue_KvlistValue{KvlistValue: mv}
			}
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 7<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			b, m.Value = b[n:], &AnyValue_BytesValue{BytesValue: append([]byte{}, x...)}
		case 8<<commonTagTypeBits | commonWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b, m.Value = b[n:], &AnyValue_StringValueStrindex{StringValueStrindex: int32(x)}
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *AnyValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *AnyValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *AnyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *AnyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		if b, err = jsontext.AppendQuote(append(b, ",\"stringValue\":"...), o.StringValue); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8")
		}
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		b = strconv.AppendBool(append(b, ",\"boolValue\":"...), o.BoolValue)
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		b = append(strconv.AppendInt(append(b, ",\"intValue\":\""...), o.IntValue, 10), '"')
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		b = commonAppendFloat(append(b, ",\"doubleValue\":"...), o.DoubleValue, 64)
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		if b, err = o.ArrayValue.ProtoAppendJSON(append(b, ",\"arrayValue\":"...)); err != nil {
			return nil, err
		}
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		if b, err = o.KvlistValue.ProtoAppendJSON(append(b, ",\"kvlistValue\":"...)); err != nil {
			return nil, err
		}
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		b = append(base64.StdEncoding.AppendEncode(append(b, ",\"bytesValue\":\""...), o.BytesValue), '"')
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		b = strconv.AppendInt(append(b, ",\"stringValueStrindex\":"...), int64(o.StringValueStrindex), 10)
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *AnyValue) UnmarshalJSON(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.AnyValue")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *AnyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = AnyValue{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *AnyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.AnyValue", "object")
	if !ok {
		return err
	}
	seen, oneofs, f := [8]bool{}, [1]bool{}, 0
	for {
		kt, more, err := commonNextKey(d)
		if !more {
			return err
		}
		key := kt.String()
		switch key {
		case "stringValue", "string_value":
			f = 0
		case "boolValue", "bool_value":
			f = 1
		case "intValue", "int_value":
			f = 2
		case "doubleValue", "double_value":
			f = 3
		case "arrayValue", "array_value":
			f = 4
		case "kvlistValue", "kvlist_value":
			f = 5
		case "bytesValue", "bytes_value":
			f = 6
		case "stringValueStrindex", "string_value_strindex":
			f = 7
		default:
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		switch f {
		case 0, 1, 2, 3, 4, 5, 6, 7:
			if oneofs[0] {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: multiple fields set for oneof value")
			}
			oneofs[0] = true
		}
		class, bits, iv, fv, bv, sv, by, tok := commonAnyValueJSONClasses[f][0], commonAnyValueJSONClasses[f][1], int64(0), float64(0), false, "", []byte(nil), jsontext.Token{}
		if class != commonClassNone {
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case commonClassSigned:
			iv, err = commonParseInt(tok, bits, "opentelemetry.proto.common.v1.AnyValue")
		case commonClassFloat:
			fv, err = commonParseFloat(tok, bits, "opentelemetry.proto.common.v1.AnyValue")
		case commonClassBool:
			bv, err = commonParseBool(tok, "opentelemetry.proto.common.v1.AnyValue")
		case commonClassString:
			sv, err = commonParseString(tok, "opentelemetry.proto.common.v1.AnyValue")
		case commonClassBytes:
			by, err = commonParseBytes(tok, "opentelemetry.proto.common.v1.AnyValue")
		}
		if err != nil {
			return err
		}
		switch f {
		case 0:
			m.Value = &AnyValue_StringValue{StringValue: sv}
		case 1:
			m.Value = &AnyValue_BoolValue{BoolValue: bv}
		case 2:
			m.Value = &AnyValue_IntValue{IntValue: iv}
		case 3:
			m.Value = &AnyValue_DoubleValue{DoubleValue: fv}
		case 4:
			mv := &ArrayValue{}
			if err := mv.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
			m.Value = &AnyValue_ArrayValue{ArrayValue: mv}
		case 5:
			mv := &KeyValueList{}
			if err := mv.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
			m.Value = &AnyValue_KvlistValue{KvlistValue: mv}
		case 6:
			m.Value = &AnyValue_BytesValue{BytesValue: by}
		case 7:
			m.Value = &AnyValue_StringValueStrindex{StringValueStrindex: int32(iv)}
		}
	}
}

var commonAnyValueJSONClasses = [8][2]int{{commonClassString, 64}, {commonClassBool, 64}, {commonClassSigned, 64}, {commonClassFloat, 64}, {commonClassNone, 64}, {commonClassNone, 64}, {commonClassBytes, 64}, {commonClassSigned, 32}}

// ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
// since oneof in AnyValue does not allow repeated fields.
type ArrayValue struct {
	// Array of values. The array may be empty (contain 0 elements).
	Values []*AnyValue

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *ArrayValue) Reset() { *m = ArrayValue{} }

func (m *ArrayValue) GetValues() []*AnyValue {
	return commonGet(m, func(m *ArrayValue) []*AnyValue { return m.Values })
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *ArrayValue) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *ArrayValue) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ArrayValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Values {
		n += 1 + commonSizeLen(v.ProtoSize())
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ArrayValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *ArrayValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *ArrayValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	for _, v := range slices.Backward(m.Values) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *ArrayValue) UnmarshalBinary(b []byte) error {
	*m = ArrayValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *ArrayValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ArrayValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			mv := &AnyValue{}
			m.Values = append(m.Values, mv)
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *ArrayValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ArrayValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *ArrayValue) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *ArrayValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.Values) > 0 {
		b = append(b, ",\"values\":["...)
		for j := range m.Values {
			if b, err = m.Values[j].ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *ArrayValue) UnmarshalJSON(b []byte) error {
	*m = ArrayValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *ArrayValue) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.ArrayValue")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *ArrayValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = ArrayValue{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *ArrayValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.ArrayValue", "object")
	if !ok {
		return err
	}
	seen, in, f := [1]bool{}, jsontext.KindInvalid, 0
	for {
		if in == jsontext.KindInvalid {
			kt, more, err := commonNextKey(d)
			if !more {
				return err
			}
			key := kt.String()
			switch key {
			case "values":
				f = 0
			default:
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull {
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 0:
				if err := commonExpectJSON(d, jsontext.KindBeginArray, "opentelemetry.proto.common.v1.ArrayValue", "array"); err != nil {
					return err
				}
				in = jsontext.KindBeginArray
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: null is not allowed in repeated fields or map values")
			}
		}
		mv := &AnyValue{}
		if err := mv.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		m.Values = append(m.Values, mv)
	}
}

// KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
// since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
// a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
// avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
// are semantically equivalent.
type KeyValueList struct {
	// A collection of key/value pairs of key-value pairs. The list may be empty (may
	// contain 0 elements).
	//
	// The keys MUST be unique (it is not allowed to have more than one
	// value with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Values []*KeyValue

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *KeyValueList) Reset() { *m = KeyValueList{} }

func (m *KeyValueList) GetValues() []*KeyValue {
	return commonGet(m, func(m *KeyValueList) []*KeyValue { return m.Values })
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *KeyValueList) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *KeyValueList) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValueList) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Values {
		n += 1 + commonSizeLen(v.ProtoSize())
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValueList) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValueList) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *KeyValueList) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	for _, v := range slices.Backward(m.Values) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *KeyValueList) UnmarshalBinary(b []byte) error {
	*m = KeyValueList{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *KeyValueList) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValueList) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			mv := &KeyValue{}
			m.Values = append(m.Values, mv)
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *KeyValueList) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValueList) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *KeyValueList) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *KeyValueList) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.Values) > 0 {
		b = append(b, ",\"values\":["...)
		for j := range m.Values {
			if b, err = m.Values[j].ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *KeyValueList) UnmarshalJSON(b []byte) error {
	*m = KeyValueList{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *KeyValueList) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.KeyValueList")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *KeyValueList) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = KeyValueList{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *KeyValueList) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.KeyValueList", "object")
	if !ok {
		return err
	}
	seen, in, f := [1]bool{}, jsontext.KindInvalid, 0
	for {
		if in == jsontext.KindInvalid {
			kt, more, err := commonNextKey(d)
			if !more {
				return err
			}
			key := kt.String()
			switch key {
			case "values":
				f = 0
			default:
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull {
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 0:
				if err := commonExpectJSON(d, jsontext.KindBeginArray, "opentelemetry.proto.common.v1.KeyValueList", "array"); err != nil {
					return err
				}
				in = jsontext.KindBeginArray
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: null is not allowed in repeated fields or map values")
			}
		}
		mv := &KeyValue{}
		if err := mv.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		m.Values = append(m.Values, mv)
	}
}

// Represents a key-value pair that is used to store Span attributes, Link
// attributes, etc.
type KeyValue struct {
	// The key name of the pair.
	// key_strindex MUST NOT be set if key is used.
	Key string
	// The value of the pair.
	Value *AnyValue
	// Reference to the string key in ProfilesDictionary.string_table.
	// key MUST NOT be set if key_strindex is used.
	//
	// Note: This is currently used exclusively in the Profiling signal.
	// Implementers of OTLP receivers for signals other than Profiling should
	// treat the presence of this key as a non-fatal issue.
	// Log an error or warning indicating an unexpected field intended for the
	// Profiling signal and process the data as if this value were absent or
	// empty, ignoring its semantic content for the non-Profiling signal.
	//
	// Status: [Alpha]
	KeyStrindex int32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *KeyValue) Reset() { *m = KeyValue{} }

func (m *KeyValue) GetKey() string { return commonGet(m, func(m *KeyValue) string { return m.Key }) }
func (m *KeyValue) GetValue() *AnyValue {
	return commonGet(m, func(m *KeyValue) *AnyValue { return m.Value })
}
func (m *KeyValue) GetKeyStrindex() int32 {
	return commonGet(m, func(m *KeyValue) int32 { return m.KeyStrindex })
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *KeyValue) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *KeyValue) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Key) > 0 {
		n += 1 + commonSizeLen(len(m.Key))
	}
	if m.Value != nil {
		n += 1 + commonSizeLen(m.Value.ProtoSize())
	}
	if m.KeyStrindex != 0 {
		n += 1 + (bits.Len64(uint64(int64(m.KeyStrindex))|1)+commonVarintPayloadBits-1)/commonVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *KeyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	if m.KeyStrindex != 0 {
		i = commonPutVarint(b, commonPutVarint(b, i, uint64(int64(m.KeyStrindex))), 3<<commonTagTypeBits|commonWireVarint)
	}
	if m.Value != nil {
		n, err := m.Value.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 2<<commonTagTypeBits|commonWireBytes)
	}
	if len(m.Key) > 0 {
		if !utf8.ValidString(m.Key) {
			return 0, errors.New(commonKeyValueKeyErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(m.Key):], m.Key), uint64(len(m.Key))), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *KeyValue) UnmarshalBinary(b []byte) error {
	*m = KeyValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *KeyValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonKeyValueKeyErrUTF8)
			}
			b, m.Key = b[n:], string(x)
		case 2<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if err := commonAlloc(&m.Value).ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 3<<commonTagTypeBits | commonWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b, m.KeyStrindex = b[n:], int32(x)
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *KeyValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *KeyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *KeyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.Key) > 0 {
		if b, err = jsontext.AppendQuote(append(b, ",\"key\":"...), m.Key); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8")
		}
	}
	if m.Value != nil {
		if b, err = m.Value.ProtoAppendJSON(append(b, ",\"value\":"...)); err != nil {
			return nil, err
		}
	}
	if m.KeyStrindex != 0 {
		b = strconv.AppendInt(append(b, ",\"keyStrindex\":"...), int64(m.KeyStrindex), 10)
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *KeyValue) UnmarshalJSON(b []byte) error {
	*m = KeyValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *KeyValue) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.KeyValue")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *KeyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = KeyValue{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *KeyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.KeyValue", "object")
	if !ok {
		return err
	}
	seen, f := [3]bool{}, 0
	for {
		kt, more, err := commonNextKey(d)
		if !more {
			return err
		}
		key := kt.String()
		switch key {
		case "key":
			f = 0
		case "value":
			f = 1
		case "keyStrindex", "key_strindex":
			f = 2
		default:
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		class, bits, iv, sv, tok := commonKeyValueJSONClasses[f][0], commonKeyValueJSONClasses[f][1], int64(0), "", jsontext.Token{}
		if class != commonClassNone {
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case commonClassSigned:
			iv, err = commonParseInt(tok, bits, "opentelemetry.proto.common.v1.KeyValue")
		case commonClassString:
			sv, err = commonParseString(tok, "opentelemetry.proto.common.v1.KeyValue")
		}
		if err != nil {
			return err
		}
		switch f {
		case 0:
			m.Key = sv
		case 1:
			if err := commonAlloc(&m.Value).ProtoMergeJSONFrom(d); err != nil {
				return err
			}
		case 2:
			m.KeyStrindex = int32(iv)
		}
	}
}

var commonKeyValueJSONClasses = [3][2]int{{commonClassString, 64}, {commonClassNone, 64}, {commonClassSigned, 32}}

// InstrumentationScope is a message representing the instrumentation scope information
// such as the fully qualified name and version.
type InstrumentationScope struct {
	// A name denoting the Instrumentation scope.
	// An empty instrumentation scope name means the name is unknown.
	Name string
	// Defines the version of the instrumentation scope.
	// An empty instrumentation scope version means the version is unknown.
	Version string
	// Additional attributes that describe the scope. [Optional].
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*KeyValue
	// The number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *InstrumentationScope) Reset() { *m = InstrumentationScope{} }

func (m *InstrumentationScope) GetName() string {
	return commonGet(m, func(m *InstrumentationScope) string { return m.Name })
}
func (m *InstrumentationScope) GetVersion() string {
	return commonGet(m, func(m *InstrumentationScope) string { return m.Version })
}
func (m *InstrumentationScope) GetAttributes() []*KeyValue {
	return commonGet(m, func(m *InstrumentationScope) []*KeyValue { return m.Attributes })
}
func (m *InstrumentationScope) GetDroppedAttributesCount() uint32 {
	return commonGet(m, func(m *InstrumentationScope) uint32 { return m.DroppedAttributesCount })
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *InstrumentationScope) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *InstrumentationScope) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *InstrumentationScope) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Name) > 0 {
		n += 1 + commonSizeLen(len(m.Name))
	}
	if len(m.Version) > 0 {
		n += 1 + commonSizeLen(len(m.Version))
	}
	for _, v := range m.Attributes {
		n += 1 + commonSizeLen(v.ProtoSize())
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + (bits.Len64(uint64(m.DroppedAttributesCount)|1)+commonVarintPayloadBits-1)/commonVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *InstrumentationScope) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *InstrumentationScope) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *InstrumentationScope) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	if m.DroppedAttributesCount != 0 {
		i = commonPutVarint(b, commonPutVarint(b, i, uint64(m.DroppedAttributesCount)), 4<<commonTagTypeBits|commonWireVarint)
	}
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = commonPutVarint(b, commonPutVarint(b, i-n, uint64(n)), 3<<commonTagTypeBits|commonWireBytes)
	}
	if len(m.Version) > 0 {
		if !utf8.ValidString(m.Version) {
			return 0, errors.New(commonInstrumentationScopeVersionErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(m.Version):], m.Version), uint64(len(m.Version))), 2<<commonTagTypeBits|commonWireBytes)
	}
	if len(m.Name) > 0 {
		if !utf8.ValidString(m.Name) {
			return 0, errors.New(commonInstrumentationScopeNameErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(m.Name):], m.Name), uint64(len(m.Name))), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *InstrumentationScope) UnmarshalBinary(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *InstrumentationScope) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *InstrumentationScope) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonInstrumentationScopeNameErrUTF8)
			}
			b, m.Name = b[n:], string(x)
		case 2<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonInstrumentationScopeVersionErrUTF8)
			}
			b, m.Version = b[n:], string(x)
		case 3<<commonTagTypeBits | commonWireBytes:
			v, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			mv := &KeyValue{}
			m.Attributes = append(m.Attributes, mv)
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 4<<commonTagTypeBits | commonWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b, m.DroppedAttributesCount = b[n:], uint32(x)
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *InstrumentationScope) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *InstrumentationScope) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *InstrumentationScope) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *InstrumentationScope) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.Name) > 0 {
		if b, err = jsontext.AppendQuote(append(b, ",\"name\":"...), m.Name); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8")
		}
	}
	if len(m.Version) > 0 {
		if b, err = jsontext.AppendQuote(append(b, ",\"version\":"...), m.Version); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8")
		}
	}
	if len(m.Attributes) > 0 {
		b = append(b, ",\"attributes\":["...)
		for j := range m.Attributes {
			if b, err = m.Attributes[j].ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
	}
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *InstrumentationScope) UnmarshalJSON(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *InstrumentationScope) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.InstrumentationScope")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *InstrumentationScope) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = InstrumentationScope{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *InstrumentationScope) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.InstrumentationScope", "object")
	if !ok {
		return err
	}
	seen, in, f := [4]bool{}, jsontext.KindInvalid, 0
	for {
		if in == jsontext.KindInvalid {
			kt, more, err := commonNextKey(d)
			if !more {
				return err
			}
			key := kt.String()
			switch key {
			case "name":
				f = 0
			case "version":
				f = 1
			case "attributes":
				f = 2
			case "droppedAttributesCount", "dropped_attributes_count":
				f = 3
			default:
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull {
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 2:
				if err := commonExpectJSON(d, jsontext.KindBeginArray, "opentelemetry.proto.common.v1.InstrumentationScope", "array"); err != nil {
					return err
				}
				in = jsontext.KindBeginArray
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: null is not allowed in repeated fields or map values")
			}
		}
		class, bits, uv, sv, tok := commonInstrumentationScopeJSONClasses[f][0], commonInstrumentationScopeJSONClasses[f][1], uint64(0), "", jsontext.Token{}
		if class != commonClassNone {
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case commonClassUnsigned:
			uv, err = commonParseUint(tok, bits, "opentelemetry.proto.common.v1.InstrumentationScope")
		case commonClassString:
			sv, err = commonParseString(tok, "opentelemetry.proto.common.v1.InstrumentationScope")
		}
		if err != nil {
			return err
		}
		switch f {
		case 0:
			m.Name = sv
		case 1:
			m.Version = sv
		case 2:
			mv := &KeyValue{}
			if err := mv.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
			m.Attributes = append(m.Attributes, mv)
		case 3:
			m.DroppedAttributesCount = uint32(uv)
		}
	}
}

var commonInstrumentationScopeJSONClasses = [4][2]int{{commonClassString, 64}, {commonClassString, 64}, {commonClassNone, 64}, {commonClassUnsigned, 32}}

// A reference to an Entity.
// Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
//
// Status: [Development]
type EntityRef struct {
	// The Schema URL, if known. This is the identifier of the Schema that the entity data
	// is recorded in. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	//
	// This schema_url applies to the data in this message and to the Resource attributes
	// referenced by id_keys and description_keys.
	// TODO: discuss if we are happy with this somewhat complicated definition of what
	// the schema_url applies to.
	//
	// This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
	SchemaUrl string
	// Defines the type of the entity. MUST not change during the lifetime of the entity.
	// For example: "service" or "host". This field is required and MUST not be empty
	// for valid entities.
	Type string
	// Attribute Keys that identify the entity.
	// MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
	// These keys MUST exist in the containing {message}.attributes.
	IdKeys []string
	// Descriptive (non-identifying) attribute keys of the entity.
	// MAY change over the lifetime of the entity. MAY be empty.
	// These attribute keys are not part of entity's identity.
	// These keys MUST exist in the containing {message}.attributes.
	DescriptionKeys []string

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *EntityRef) Reset() { *m = EntityRef{} }

func (m *EntityRef) GetSchemaUrl() string {
	return commonGet(m, func(m *EntityRef) string { return m.SchemaUrl })
}
func (m *EntityRef) GetType() string {
	return commonGet(m, func(m *EntityRef) string { return m.Type })
}
func (m *EntityRef) GetIdKeys() []string {
	return commonGet(m, func(m *EntityRef) []string { return m.IdKeys })
}
func (m *EntityRef) GetDescriptionKeys() []string {
	return commonGet(m, func(m *EntityRef) []string { return m.DescriptionKeys })
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *EntityRef) ProtoUnknownFields() []byte {
	return commonGet(m, func(m *EntityRef) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *EntityRef) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.SchemaUrl) > 0 {
		n += 1 + commonSizeLen(len(m.SchemaUrl))
	}
	if len(m.Type) > 0 {
		n += 1 + commonSizeLen(len(m.Type))
	}
	for _, v := range m.IdKeys {
		n += 1 + commonSizeLen(len(v))
	}
	for _, v := range m.DescriptionKeys {
		n += 1 + commonSizeLen(len(v))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *EntityRef) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *EntityRef) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return commonAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *EntityRef) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	for _, v := range slices.Backward(m.DescriptionKeys) {
		if !utf8.ValidString(v) {
			return 0, errors.New(commonEntityRefDescriptionKeysErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 4<<commonTagTypeBits|commonWireBytes)
	}
	for _, v := range slices.Backward(m.IdKeys) {
		if !utf8.ValidString(v) {
			return 0, errors.New(commonEntityRefIdKeysErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 3<<commonTagTypeBits|commonWireBytes)
	}
	if len(m.Type) > 0 {
		if !utf8.ValidString(m.Type) {
			return 0, errors.New(commonEntityRefTypeErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(m.Type):], m.Type), uint64(len(m.Type))), 2<<commonTagTypeBits|commonWireBytes)
	}
	if len(m.SchemaUrl) > 0 {
		if !utf8.ValidString(m.SchemaUrl) {
			return 0, errors.New(commonEntityRefSchemaUrlErrUTF8)
		}
		i = commonPutVarint(b, commonPutVarint(b, i-copy(b[i-len(m.SchemaUrl):], m.SchemaUrl), uint64(len(m.SchemaUrl))), 1<<commonTagTypeBits|commonWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *EntityRef) UnmarshalBinary(b []byte) error {
	*m = EntityRef{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *EntityRef) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *EntityRef) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= commonMaxDepth {
		return errors.New(commonErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonEntityRefSchemaUrlErrUTF8)
			}
			b, m.SchemaUrl = b[n:], string(x)
		case 2<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonEntityRefTypeErrUTF8)
			}
			b, m.Type = b[n:], string(x)
		case 3<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonEntityRefIdKeysErrUTF8)
			}
			b, m.IdKeys = b[n:], append(m.IdKeys, string(x))
		case 4<<commonTagTypeBits | commonWireBytes:
			x, n := commonReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(commonEntityRefDescriptionKeysErrUTF8)
			}
			b, m.DescriptionKeys = b[n:], append(m.DescriptionKeys, string(x))
		default:
			n, err := commonSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(commonErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *EntityRef) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *EntityRef) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *EntityRef) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return commonWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *EntityRef) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.SchemaUrl) > 0 {
		if b, err = jsontext.AppendQuote(append(b, ",\"schemaUrl\":"...), m.SchemaUrl); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8")
		}
	}
	if len(m.Type) > 0 {
		if b, err = jsontext.AppendQuote(append(b, ",\"type\":"...), m.Type); err != nil {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8")
		}
	}
	if len(m.IdKeys) > 0 {
		b = append(b, ",\"idKeys\":["...)
		for j := range m.IdKeys {
			if b, err = jsontext.AppendQuote(b, m.IdKeys[j]); err != nil {
				return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8")
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
	}
	if len(m.DescriptionKeys) > 0 {
		b = append(b, ",\"descriptionKeys\":["...)
		for j := range m.DescriptionKeys {
			if b, err = jsontext.AppendQuote(b, m.DescriptionKeys[j]); err != nil {
				return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8")
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
	}
	return commonCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *EntityRef) UnmarshalJSON(b []byte) error {
	*m = EntityRef{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *EntityRef) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return commonEndJSON(d, m.ProtoMergeJSONFrom(d), "opentelemetry.proto.common.v1.EntityRef")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *EntityRef) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := commonStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = EntityRef{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *EntityRef) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := commonOpenJSON(d, jsontext.KindBeginObject, "opentelemetry.proto.common.v1.EntityRef", "object")
	if !ok {
		return err
	}
	seen, in, f := [4]bool{}, jsontext.KindInvalid, 0
	for {
		if in == jsontext.KindInvalid {
			kt, more, err := commonNextKey(d)
			if !more {
				return err
			}
			key := kt.String()
			switch key {
			case "schemaUrl", "schema_url":
				f = 0
			case "type":
				f = 1
			case "idKeys", "id_keys":
				f = 2
			case "descriptionKeys", "description_keys":
				f = 3
			default:
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull {
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 2, 3:
				if err := commonExpectJSON(d, jsontext.KindBeginArray, "opentelemetry.proto.common.v1.EntityRef", "array"); err != nil {
					return err
				}
				in = jsontext.KindBeginArray
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: null is not allowed in repeated fields or map values")
			}
		}
		class, sv, tok := commonEntityRefJSONClasses[f], "", jsontext.Token{}
		if class != commonClassNone {
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case commonClassString:
			sv, err = commonParseString(tok, "opentelemetry.proto.common.v1.EntityRef")
		}
		if err != nil {
			return err
		}
		switch f {
		case 0:
			m.SchemaUrl = sv
		case 1:
			m.Type = sv
		case 2:
			m.IdKeys = append(m.IdKeys, sv)
		case 3:
			m.DescriptionKeys = append(m.DescriptionKeys, sv)
		}
	}
}

var commonEntityRefJSONClasses = [4]int{commonClassString, commonClassString, commonClassString, commonClassString}

func commonPutVarint(b []byte, i int, u uint64) int {
	if u < commonVarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + commonVarintPayloadBits - 1) / commonVarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}

func commonPutFixed64(b []byte, i int, u uint64) int {
	binary.LittleEndian.PutUint64(b[i-commonFixed64Size:], u)
	return i - commonFixed64Size
}

func commonPutBool(b []byte, i int, v bool) int {
	b[i-1] = 0
	if v {
		b[i-1] = 1
	}
	return i - 1
}

func commonSizeLen(l int) int {
	return l + (bits.Len64(uint64(l)|1)+commonVarintPayloadBits-1)/commonVarintPayloadBits
}

func commonReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}

func commonSkipField(b []byte, t uint64, depth int) (int, error) {
	switch t & commonTagTypeMask {
	case commonWireVarint:
		if _, n := binary.Uvarint(b); n > 0 {
			return n, nil
		}
	case commonWireFixed64:
		if len(b) >= commonFixed64Size {
			return commonFixed64Size, nil
		}
	case commonWireBytes:
		if _, n := commonReadBytes(b); n >= 0 {
			return n, nil
		}
	case commonWireStartGroup:
		return commonSkipGroup(b, int32(t>>commonTagTypeBits), depth)
	case commonWireFixed32:
		if len(b) >= commonFixed32Size {
			return commonFixed32Size, nil
		}
	}
	return 0, errors.New(commonErrParse)
}

func commonSkipGroup(b []byte, num int32, depth int) (int, error) {
	var stk [commonSkipStackSize]int32
	open := append(stk[:0], num)
	n := 0
	for len(open) > 0 {
		if depth+len(open) > commonMaxDepth {
			return 0, errors.New(commonErrDepth)
		}
		t, k := binary.Uvarint(b[n:])
		if k <= 0 || t>>commonTagTypeBits == 0 || t>>commonTagTypeBits > commonMaxFieldNumber {
			return 0, errors.New(commonErrParse)
		}
		n += k
		switch t & commonTagTypeMask {
		case commonWireStartGroup:
			open = append(open, int32(t>>commonTagTypeBits))
		case commonWireEndGroup:
			if open[len(open)-1] != int32(t>>commonTagTypeBits) {
				return 0, errors.New(commonErrParse)
			}
			open = open[:len(open)-1]
		default:
			k, err := commonSkipField(b[n:], t, depth)
			if err != nil {
				return 0, err
			}
			n += k
		}
	}
	return n, nil
}

func commonAppended(b []byte, size, n int, err error) ([]byte, error) {
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}

func commonGet[M, T any](m *M, f func(*M) T) (t T) {
	if m != nil {
		t = f(m)
	}
	return t
}

func commonAlloc[T any](p **T) *T {
	if *p == nil {
		*p = new(T)
	}
	return *p
}

func commonWriteJSON(e *jsontext.Encoder, b []byte, err error) error {
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

func commonAppendFloat(b []byte, f float64, bits int) []byte {
	switch {
	case math.IsNaN(f):
		return append(b, `"NaN"`...)
	case math.IsInf(f, 1):
		return append(b, `"Infinity"`...)
	case math.IsInf(f, -1):
		return append(b, `"-Infinity"`...)
	}
	return jsontext.AppendFloat(b, f, bits)
}

func commonCloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}

func commonEndJSON(d *jsontext.Decoder, err error, name string) error {
	if err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return commonJSONError(name, "unexpected data after JSON value")
	}
	return nil
}

func commonStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return nil, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}

func commonOpenJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) (bool, error) {
	if d.PeekKind() == jsontext.KindNull {
		return false, d.SkipValue()
	}
	err := commonExpectJSON(d, kind, name, what)
	return err == nil, err
}

func commonExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return commonJSONError(name, "expected a JSON "+what)
	}
	return nil
}

func commonNextKey(d *jsontext.Decoder) (jsontext.Token, bool, error) {
	if d.PeekKind() == jsontext.KindEndObject {
		_, err := d.ReadToken()
		return jsontext.Token{}, false, err
	}
	tok, err := d.ReadToken()
	return tok, err == nil, err
}

func commonParseInt(tok jsontext.Token, bits int, name string) (int64, error) {
	s, err := commonJSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	if v, err := strconv.ParseInt(s, 10, bits); err == nil {
		return v, nil
	}
	n := commonExactInt(s)
	if n == nil || !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
		return 0, commonJSONError(name, commonErrInvalidInteger+s)
	}
	return n.Int64(), nil
}

func commonParseUint(tok jsontext.Token, bits int, name string) (uint64, error) {
	s, err := commonJSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	if v, err := strconv.ParseUint(s, 10, bits); err == nil {
		return v, nil
	}
	n := commonExactInt(s)
	if n == nil || !n.IsUint64() || (bits == 32 && n.Uint64() > math.MaxUint32) {
		return 0, commonJSONError(name, commonErrInvalidInteger+s)
	}
	return n.Uint64(), nil
}

func commonExactInt(s string) *big.Int {
	if i := strings.IndexAny(s, "eE"); i >= 0 {
		if e, err := strconv.Atoi(s[i+1:]); err != nil || e > commonMaxJSONExponent || e < -commonMaxJSONExponent {
			return nil
		}
	}
	r, ok := new(big.Rat).SetString(s)
	if !ok || !r.IsInt() {
		return nil
	}
	return r.Num()
}

func commonParseFloat(tok jsontext.Token, bits int, name string) (float64, error) {
	if tok.Kind() == jsontext.KindString {
		switch tok.String() {
		case "NaN":
			return math.NaN(), nil
		case "Infinity":
			return math.Inf(1), nil
		case "-Infinity":
			return math.Inf(-1), nil
		}
	}
	s, err := commonJSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	v, err := strconv.ParseFloat(s, bits)
	if err != nil {
		return 0, commonJSONError(name, commonErrInvalidNumber+s)
	}
	return v, nil
}

func commonJSONNumber(tok jsontext.Token, name string) (string, error) {
	s := tok.String()
	if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
		return "", commonJSONError(name, commonErrInvalidNumber+s)
	}
	return s, nil
}

func commonParseBool(tok jsontext.Token, name string) (bool, error) {
	switch tok.Kind() {
	case jsontext.KindTrue:
		return true, nil
	case jsontext.KindFalse:
		return false, nil
	}
	return false, commonJSONError(name, "invalid boolean "+tok.String())
}

func commonParseString(tok jsontext.Token, name string) (string, error) {
	if tok.Kind() != jsontext.KindString {
		return "", commonJSONError(name, "invalid string "+tok.String())
	}
	return tok.String(), nil
}

func commonParseBytes(tok jsontext.Token, name string) ([]byte, error) {
	s := tok.String()
	if tok.Kind() == jsontext.KindString {
		enc := base64.StdEncoding
		if strings.ContainsAny(s, "-_") {
			enc = base64.URLEncoding
		}
		if len(s)%commonBase64Quantum != 0 {
			enc = enc.WithPadding(base64.NoPadding)
		}
		if by, err := enc.DecodeString(s); err == nil {
			return by, nil
		}
	}
	return nil, commonJSONError(name, "invalid bytes "+s)
}

func commonJSONError(name, msg string) error {
	return errors.New("proto: " + name + ": " + msg)
}
