// Code generated by cotorp. DO NOT EDIT.
// source: common/v1/common.proto

package v1

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

// Represents any type of attribute value. AnyValue may contain a
// primitive value such as a string or integer or it may contain an arbitrary nested
// object containing arrays, key-value lists and primitives.
type AnyValue struct {
	// The value is one of the listed fields. It is valid for all values to be unspecified
	// in which case this AnyValue is considered to be "empty".
	//
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	//	*AnyValue_BytesValue
	//	*AnyValue_StringValueStrindex
	Value isAnyValue_Value

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *AnyValue) Reset() { *m = AnyValue{} }

func (m *AnyValue) GetValue() isAnyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *AnyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*AnyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *AnyValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*AnyValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *AnyValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*AnyValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *AnyValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*AnyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *AnyValue) GetArrayValue() *ArrayValue {
	if x, ok := m.GetValue().(*AnyValue_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}

func (m *AnyValue) GetKvlistValue() *KeyValueList {
	if x, ok := m.GetValue().(*AnyValue_KvlistValue); ok {
		return x.KvlistValue
	}
	return nil
}

func (m *AnyValue) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*AnyValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *AnyValue) GetStringValueStrindex() int32 {
	if x, ok := m.GetValue().(*AnyValue_StringValueStrindex); ok {
		return x.StringValueStrindex
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *AnyValue) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

type AnyValue_BoolValue struct {
	BoolValue bool
}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

type AnyValue_IntValue struct {
	IntValue int64
}

func (*AnyValue_IntValue) isAnyValue_Value() {}

type AnyValue_DoubleValue struct {
	DoubleValue float64
}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

type AnyValue_ArrayValue struct {
	ArrayValue *ArrayValue
}

func (*AnyValue_ArrayValue) isAnyValue_Value() {}

type AnyValue_KvlistValue struct {
	KvlistValue *KeyValueList
}

func (*AnyValue_KvlistValue) isAnyValue_Value() {}

type AnyValue_BytesValue struct {
	BytesValue []byte
}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

// Reference to the string value in ProfilesDictionary.string_table.
//
// Note: This is currently used exclusively in the Profiling signal.
// Implementers of OTLP receivers for signals other than Profiling should
// treat the presence of this value as a non-fatal issue.
// Log an error or warning indicating an unexpected field intended for the
// Profiling signal and process the data as if this value were absent or
// empty, ignoring its semantic content for the non-Profiling signal.
//
// Status: [Alpha]
type AnyValue_StringValueStrindex struct {
	StringValueStrindex int32
}

func (*AnyValue_StringValueStrindex) isAnyValue_Value() {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *AnyValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	switch o := m.Value.(type) {
	case *AnyValue_StringValue:
		n += 1 + len(o.StringValue) + (bits.Len64((uint64(len(o.StringValue)))|1)+6)/7
	case *AnyValue_BoolValue:
		n += 1 + 1
	case *AnyValue_IntValue:
		n += 1 + (bits.Len64((uint64(o.IntValue))|1)+6)/7
	case *AnyValue_DoubleValue:
		n += 1 + 8
	case *AnyValue_ArrayValue:
		{
			l := o.ArrayValue.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	case *AnyValue_KvlistValue:
		{
			l := o.KvlistValue.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	case *AnyValue_BytesValue:
		n += 1 + len(o.BytesValue) + (bits.Len64((uint64(len(o.BytesValue)))|1)+6)/7
	case *AnyValue_StringValueStrindex:
		n += 1 + (bits.Len64((uint64(int64(o.StringValueStrindex)))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *AnyValue) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *AnyValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *AnyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		u = uint64(int64(o.StringValueStrindex))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x40
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		i -= len(o.BytesValue)
		copy(b[i:], o.BytesValue)
		u = uint64(len(o.BytesValue))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x3a
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		{
			n, err := o.KvlistValue.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x32
		}
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		{
			n, err := o.ArrayValue.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x2a
		}
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		i -= 8
		binary.LittleEndian.PutUint64(b[i:], math.Float64bits(o.DoubleValue))
		i--
		b[i] = 0x21
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		u = uint64(o.IntValue)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x18
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		i--
		if o.BoolValue {
			b[i] = 1
		} else {
			b[i] = 0
		}
		i--
		b[i] = 0x10
	}
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		if !utf8.ValidString(o.StringValue) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8")
		}
		i -= len(o.StringValue)
		copy(b[i:], o.StringValue)
		u = uint64(len(o.StringValue))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x0a
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *AnyValue) UnmarshalBinary(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *AnyValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8")
				}
				b = b[n:]
				m.Value = &AnyValue_StringValue{StringValue: string(x)}
				continue
			}
		case 2:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Value = &AnyValue_BoolValue{BoolValue: x != 0}
				continue
			}
		case 3:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Value = &AnyValue_IntValue{IntValue: int64(x)}
				continue
			}
		case 4:
			if typ == 1 {
				if len(b) < 8 {
					goto errParse
				}
				x, n := binary.LittleEndian.Uint64(b), 8
				b = b[n:]
				m.Value = &AnyValue_DoubleValue{DoubleValue: math.Float64frombits(x)}
				continue
			}
		case 5:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				var mv *ArrayValue
				if o, ok := m.Value.(*AnyValue_ArrayValue); ok && o.ArrayValue != nil {
					mv = o.ArrayValue
				} else {
					mv = &ArrayValue{}
					m.Value = &AnyValue_ArrayValue{ArrayValue: mv}
				}
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 6:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				var mv *KeyValueList
				if o, ok := m.Value.(*AnyValue_KvlistValue); ok && o.KvlistValue != nil {
					mv = o.KvlistValue
				} else {
					mv = &KeyValueList{}
					m.Value = &AnyValue_KvlistValue{KvlistValue: mv}
				}
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 7:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				b = b[n:]
				m.Value = &AnyValue_BytesValue{BytesValue: append([]byte{}, x...)}
				continue
			}
		case 8:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Value = &AnyValue_StringValueStrindex{StringValueStrindex: int32(x)}
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *AnyValue) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *AnyValue) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *AnyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		b = append(b, "\"stringValue\":"...)
		if !utf8.ValidString(o.StringValue) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(o.StringValue); ci++ {
			switch c := o.StringValue[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		b = append(b, "\"boolValue\":"...)
		if o.BoolValue {
			b = append(b, "true"...)
		} else {
			b = append(b, "false"...)
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		b = append(b, "\"intValue\":"...)
		b = append(b, '"')
		b = strconv.AppendInt(b, o.IntValue, 10)
		b = append(b, '"')
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		b = append(b, "\"doubleValue\":"...)
		switch fl := float64(o.DoubleValue); {
		case math.IsNaN(fl):
			b = append(b, `"NaN"`...)
		case math.IsInf(fl, 1):
			b = append(b, `"Infinity"`...)
		case math.IsInf(fl, -1):
			b = append(b, `"-Infinity"`...)
		default:
			b = strconv.AppendFloat(b, fl, 'g', -1, 64)
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		b = append(b, "\"arrayValue\":"...)
		{
			var err error
			if b, err = o.ArrayValue.ProtoAppendJSON(b); err != nil {
				return nil, err
			}
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		b = append(b, "\"kvlistValue\":"...)
		{
			var err error
			if b, err = o.KvlistValue.ProtoAppendJSON(b); err != nil {
				return nil, err
			}
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		b = append(b, "\"bytesValue\":"...)
		{
			n := base64.StdEncoding.EncodedLen(len(o.BytesValue))
			b = append(b, '"')
			l := len(b)
			b = slices.Grow(b, n)[:l+n]
			base64.StdEncoding.Encode(b[l:], o.BytesValue)
			b = append(b, '"')
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		b = append(b, "\"stringValueStrindex\":"...)
		b = strconv.AppendInt(b, int64(o.StringValueStrindex), 10)
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *AnyValue) UnmarshalJSON(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [8]bool
	var oneofs [1]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "stringValue", "string_value":
			f = 0
		case "boolValue", "bool_value":
			f = 1
		case "intValue", "int_value":
			f = 2
		case "doubleValue", "double_value":
			f = 3
		case "arrayValue", "array_value":
			f = 4
		case "kvlistValue", "kvlist_value":
			f = 5
		case "bytesValue", "bytes_value":
			f = 6
		case "stringValueStrindex", "string_value_strindex":
			f = 7
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0, 1, 2, 3, 4, 5, 6, 7:
			if null {
				continue
			}
			if oneofs[0] {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: multiple fields set for oneof value")
			}
			oneofs[0] = true
			jobs = append(jobs, job{f: f, raw: raw})
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		class := 0
		bits := 64
		var iv int64
		var fv float64
		var bv bool
		var sv string
		var by []byte
		switch jb.f {
		case 7:
			class, bits = 1, 32
		case 2:
			class, bits = 1, 64
		case 3:
			class, bits = 3, 64
		case 1:
			class = 4
		case 0:
			class = 5
		case 6:
			class = 6
		}
		switch class {
		case 1:
			s := string(raw)
			if raw[0] == '"' {
				if err := json.Unmarshal(raw, &s); err != nil {
					return err
				}
			}
			if s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !json.Valid([]byte(s)) {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid number " + string(raw))
			}
			var err error
			iv, err = strconv.ParseInt(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > 100 || e < -100 {
						return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid integer " + string(raw))
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid integer " + string(raw))
				}
				n := r.Num()
				if !n.IsInt64() || (bits == 32 && (n.Int64() < -1<<31 || n.Int64() > 1<<31-1)) {
					return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid integer " + string(raw))
				}
				iv = n.Int64()
			}
		case 3:
			s := string(raw)
			special := false
			if raw[0] == '"' {
				if err := json.Unmarshal(raw, &s); err != nil {
					return err
				}
				switch s {
				case "NaN":
					fv, special = math.NaN(), true
				case "Infinity":
					fv, special = math.Inf(1), true
				case "-Infinity":
					fv, special = math.Inf(-1), true
				}
			}
			if !special {
				if s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !json.Valid([]byte(s)) {
					return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid number " + string(raw))
				}
				var err error
				if fv, err = strconv.ParseFloat(s, bits); err != nil {
					return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid number " + string(raw))
				}
			}
		case 4:
			switch string(raw) {
			case "true":
				bv = true
			case "false":
			default:
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid boolean " + string(raw))
			}
		case 5:
			if raw[0] != '"' || !utf8.Valid(raw) {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid string " + string(raw))
			}
			if err := json.Unmarshal(raw, &sv); err != nil {
				return err
			}
		case 6:
			var s string
			if raw[0] != '"' {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid bytes " + string(raw))
			}
			if err := json.Unmarshal(raw, &s); err != nil {
				return err
			}
			// Accept standard and URL-safe alphabets, with or without padding.
			enc := base64.StdEncoding
			if strings.ContainsAny(s, "-_") {
				enc = base64.URLEncoding
			}
			if len(s)%4 != 0 {
				enc = enc.WithPadding(base64.NoPadding)
			}
			var err error
			if by, err = enc.DecodeString(s); err != nil {
				return errors.New("proto: opentelemetry.proto.common.v1.AnyValue: invalid bytes " + string(raw))
			}
		}
		switch jb.f {
		case 0:
			m.Value = &AnyValue_StringValue{StringValue: sv}
		case 1:
			m.Value = &AnyValue_BoolValue{BoolValue: bv}
		case 2:
			m.Value = &AnyValue_IntValue{IntValue: iv}
		case 3:
			m.Value = &AnyValue_DoubleValue{DoubleValue: fv}
		case 4:
			mv := &ArrayValue{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Value = &AnyValue_ArrayValue{ArrayValue: mv}
		case 5:
			mv := &KeyValueList{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Value = &AnyValue_KvlistValue{KvlistValue: mv}
		case 6:
			m.Value = &AnyValue_BytesValue{BytesValue: by}
		case 7:
			m.Value = &AnyValue_StringValueStrindex{StringValueStrindex: int32(iv)}
		}
	}
	return nil
}

// ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
// since oneof in AnyValue does not allow repeated fields.
type ArrayValue struct {
	// Array of values. The array may be empty (contain 0 elements).
	Values []*AnyValue

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *ArrayValue) Reset() { *m = ArrayValue{} }

func (m *ArrayValue) GetValues() []*AnyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *ArrayValue) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ArrayValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Values {
		{
			l := v.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ArrayValue) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *ArrayValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *ArrayValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for j := len(m.Values) - 1; j >= 0; j-- {
		{
			n, err := m.Values[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x0a
		}
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *ArrayValue) UnmarshalBinary(b []byte) error {
	*m = ArrayValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *ArrayValue) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ArrayValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				mv := &AnyValue{}
				m.Values = append(m.Values, mv)
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *ArrayValue) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ArrayValue) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *ArrayValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Values) > 0 {
		b = append(b, "\"values\":["...)
		for j := range m.Values {
			{
				var err error
				if b, err = m.Values[j].ProtoAppendJSON(b); err != nil {
					return nil, err
				}
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *ArrayValue) UnmarshalJSON(b []byte) error {
	*m = ArrayValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *ArrayValue) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [1]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "values":
			f = 0
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0:
			if null {
				continue
			}
			ad := json.NewDecoder(bytes.NewReader(raw))
			ad.UseNumber()
			if t, err := ad.Token(); err != nil || t != json.Delim('[') {
				return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: expected a JSON array")
			}
			for ad.More() {
				var e json.RawMessage
				if err := ad.Decode(&e); err != nil {
					return err
				}
				if string(e) == "null" {
					return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: null is not allowed in repeated fields or map values")
				}
				jobs = append(jobs, job{f: f, raw: e})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.ArrayValue: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		switch jb.f {
		case 0:
			mv := &AnyValue{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Values = append(m.Values, mv)
		}
	}
	return nil
}

// KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
// since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
// a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
// avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
// are semantically equivalent.
type KeyValueList struct {
	// A collection of key/value pairs of key-value pairs. The list may be empty (may
	// contain 0 elements).
	//
	// The keys MUST be unique (it is not allowed to have more than one
	// value with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Values []*KeyValue

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *KeyValueList) Reset() { *m = KeyValueList{} }

func (m *KeyValueList) GetValues() []*KeyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *KeyValueList) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValueList) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Values {
		{
			l := v.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValueList) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValueList) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *KeyValueList) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for j := len(m.Values) - 1; j >= 0; j-- {
		{
			n, err := m.Values[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x0a
		}
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *KeyValueList) UnmarshalBinary(b []byte) error {
	*m = KeyValueList{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *KeyValueList) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValueList) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				mv := &KeyValue{}
				m.Values = append(m.Values, mv)
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *KeyValueList) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValueList) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *KeyValueList) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Values) > 0 {
		b = append(b, "\"values\":["...)
		for j := range m.Values {
			{
				var err error
				if b, err = m.Values[j].ProtoAppendJSON(b); err != nil {
					return nil, err
				}
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *KeyValueList) UnmarshalJSON(b []byte) error {
	*m = KeyValueList{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *KeyValueList) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [1]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "values":
			f = 0
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0:
			if null {
				continue
			}
			ad := json.NewDecoder(bytes.NewReader(raw))
			ad.UseNumber()
			if t, err := ad.Token(); err != nil || t != json.Delim('[') {
				return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: expected a JSON array")
			}
			for ad.More() {
				var e json.RawMessage
				if err := ad.Decode(&e); err != nil {
					return err
				}
				if string(e) == "null" {
					return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: null is not allowed in repeated fields or map values")
				}
				jobs = append(jobs, job{f: f, raw: e})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.KeyValueList: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		switch jb.f {
		case 0:
			mv := &KeyValue{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Values = append(m.Values, mv)
		}
	}
	return nil
}

// Represents a key-value pair that is used to store Span attributes, Link
// attributes, etc.
type KeyValue struct {
	// The key name of the pair.
	// key_strindex MUST NOT be set if key is used.
	Key string
	// The value of the pair.
	Value *AnyValue
	// Reference to the string key in ProfilesDictionary.string_table.
	// key MUST NOT be set if key_strindex is used.
	//
	// Note: This is currently used exclusively in the Profiling signal.
	// Implementers of OTLP receivers for signals other than Profiling should
	// treat the presence of this key as a non-fatal issue.
	// Log an error or warning indicating an unexpected field intended for the
	// Profiling signal and process the data as if this value were absent or
	// empty, ignoring its semantic content for the non-Profiling signal.
	//
	// Status: [Alpha]
	KeyStrindex int32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *KeyValue) Reset() { *m = KeyValue{} }

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() *AnyValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetKeyStrindex() int32 {
	if m != nil {
		return m.KeyStrindex
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *KeyValue) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Key) > 0 {
		n += 1 + len(m.Key) + (bits.Len64((uint64(len(m.Key)))|1)+6)/7
	}
	if m.Value != nil {
		{
			l := m.Value.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	if m.KeyStrindex != 0 {
		n += 1 + (bits.Len64((uint64(int64(m.KeyStrindex)))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValue) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *KeyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.KeyStrindex != 0 {
		u = uint64(int64(m.KeyStrindex))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x18
	}
	if m.Value != nil {
		{
			n, err := m.Value.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x12
		}
	}
	if len(m.Key) > 0 {
		if !utf8.ValidString(m.Key) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8")
		}
		i -= len(m.Key)
		copy(b[i:], m.Key)
		u = uint64(len(m.Key))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x0a
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *KeyValue) UnmarshalBinary(b []byte) error {
	*m = KeyValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *KeyValue) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8")
				}
				b = b[n:]
				m.Key = string(x)
				continue
			}
		case 2:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				if m.Value == nil {
					m.Value = &AnyValue{}
				}
				mv := m.Value
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 3:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.KeyStrindex = int32(x)
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *KeyValue) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValue) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *KeyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Key) > 0 {
		b = append(b, "\"key\":"...)
		if !utf8.ValidString(m.Key) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(m.Key); ci++ {
			switch c := m.Key[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if m.Value != nil {
		b = append(b, "\"value\":"...)
		{
			var err error
			if b, err = m.Value.ProtoAppendJSON(b); err != nil {
				return nil, err
			}
		}
		b = append(b, ',')
	}
	if m.KeyStrindex != 0 {
		b = append(b, "\"keyStrindex\":"...)
		b = strconv.AppendInt(b, int64(m.KeyStrindex), 10)
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *KeyValue) UnmarshalJSON(b []byte) error {
	*m = KeyValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *KeyValue) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [3]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "key":
			f = 0
		case "value":
			f = 1
		case "keyStrindex", "key_strindex":
			f = 2
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0, 1, 2:
			if !null {
				jobs = append(jobs, job{f: f, raw: raw})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		class := 0
		bits := 64
		var iv int64
		var sv string
		switch jb.f {
		case 2:
			class, bits = 1, 32
		case 0:
			class = 5
		}
		switch class {
		case 1:
			s := string(raw)
			if raw[0] == '"' {
				if err := json.Unmarshal(raw, &s); err != nil {
					return err
				}
			}
			if s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !json.Valid([]byte(s)) {
				return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: invalid number " + string(raw))
			}
			var err error
			iv, err = strconv.ParseInt(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > 100 || e < -100 {
						return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: invalid integer " + string(raw))
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: invalid integer " + string(raw))
				}
				n := r.Num()
				if !n.IsInt64() || (bits == 32 && (n.Int64() < -1<<31 || n.Int64() > 1<<31-1)) {
					return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: invalid integer " + string(raw))
				}
				iv = n.Int64()
			}
		case 5:
			if raw[0] != '"' || !utf8.Valid(raw) {
				return errors.New("proto: opentelemetry.proto.common.v1.KeyValue: invalid string " + string(raw))
			}
			if err := json.Unmarshal(raw, &sv); err != nil {
				return err
			}
		}
		switch jb.f {
		case 0:
			m.Key = sv
		case 1:
			if m.Value == nil {
				m.Value = &AnyValue{}
			}
			if err := m.Value.ProtoMergeJSON(raw); err != nil {
				return err
			}
		case 2:
			m.KeyStrindex = int32(iv)
		}
	}
	return nil
}

// InstrumentationScope is a message representing the instrumentation scope information
// such as the fully qualified name and version.
type InstrumentationScope struct {
	// A name denoting the Instrumentation scope.
	// An empty instrumentation scope name means the name is unknown.
	Name string
	// Defines the version of the instrumentation scope.
	// An empty instrumentation scope version means the version is unknown.
	Version string
	// Additional attributes that describe the scope. [Optional].
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*KeyValue
	// The number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *InstrumentationScope) Reset() { *m = InstrumentationScope{} }

func (m *InstrumentationScope) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstrumentationScope) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstrumentationScope) GetAttributes() []*KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *InstrumentationScope) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *InstrumentationScope) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *InstrumentationScope) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Name) > 0 {
		n += 1 + len(m.Name) + (bits.Len64((uint64(len(m.Name)))|1)+6)/7
	}
	if len(m.Version) > 0 {
		n += 1 + len(m.Version) + (bits.Len64((uint64(len(m.Version)))|1)+6)/7
	}
	for _, v := range m.Attributes {
		{
			l := v.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + (bits.Len64((uint64(m.DroppedAttributesCount))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *InstrumentationScope) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *InstrumentationScope) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *InstrumentationScope) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.DroppedAttributesCount != 0 {
		u = uint64(m.DroppedAttributesCount)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x20
	}
	for j := len(m.Attributes) - 1; j >= 0; j-- {
		{
			n, err := m.Attributes[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x1a
		}
	}
	if len(m.Version) > 0 {
		if !utf8.ValidString(m.Version) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8")
		}
		i -= len(m.Version)
		copy(b[i:], m.Version)
		u = uint64(len(m.Version))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x12
	}
	if len(m.Name) > 0 {
		if !utf8.ValidString(m.Name) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8")
		}
		i -= len(m.Name)
		copy(b[i:], m.Name)
		u = uint64(len(m.Name))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x0a
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *InstrumentationScope) UnmarshalBinary(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *InstrumentationScope) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *InstrumentationScope) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8")
				}
				b = b[n:]
				m.Name = string(x)
				continue
			}
		case 2:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8")
				}
				b = b[n:]
				m.Version = string(x)
				continue
			}
		case 3:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				mv := &KeyValue{}
				m.Attributes = append(m.Attributes, mv)
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 4:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.DroppedAttributesCount = uint32(x)
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *InstrumentationScope) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *InstrumentationScope) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *InstrumentationScope) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Name) > 0 {
		b = append(b, "\"name\":"...)
		if !utf8.ValidString(m.Name) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(m.Name); ci++ {
			switch c := m.Name[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.Version) > 0 {
		b = append(b, "\"version\":"...)
		if !utf8.ValidString(m.Version) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(m.Version); ci++ {
			switch c := m.Version[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.Attributes) > 0 {
		b = append(b, "\"attributes\":["...)
		for j := range m.Attributes {
			{
				var err error
				if b, err = m.Attributes[j].ProtoAppendJSON(b); err != nil {
					return nil, err
				}
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if m.DroppedAttributesCount != 0 {
		b = append(b, "\"droppedAttributesCount\":"...)
		b = strconv.AppendUint(b, uint64(m.DroppedAttributesCount), 10)
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *InstrumentationScope) UnmarshalJSON(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *InstrumentationScope) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [4]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "name":
			f = 0
		case "version":
			f = 1
		case "attributes":
			f = 2
		case "droppedAttributesCount", "dropped_attributes_count":
			f = 3
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0, 1, 3:
			if !null {
				jobs = append(jobs, job{f: f, raw: raw})
			}
		case 2:
			if null {
				continue
			}
			ad := json.NewDecoder(bytes.NewReader(raw))
			ad.UseNumber()
			if t, err := ad.Token(); err != nil || t != json.Delim('[') {
				return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: expected a JSON array")
			}
			for ad.More() {
				var e json.RawMessage
				if err := ad.Decode(&e); err != nil {
					return err
				}
				if string(e) == "null" {
					return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: null is not allowed in repeated fields or map values")
				}
				jobs = append(jobs, job{f: f, raw: e})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		class := 0
		bits := 64
		var uv uint64
		var sv string
		switch jb.f {
		case 3:
			class, bits = 2, 32
		case 0, 1:
			class = 5
		}
		switch class {
		case 2:
			s := string(raw)
			if raw[0] == '"' {
				if err := json.Unmarshal(raw, &s); err != nil {
					return err
				}
			}
			if s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !json.Valid([]byte(s)) {
				return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: invalid number " + string(raw))
			}
			var err error
			uv, err = strconv.ParseUint(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > 100 || e < -100 {
						return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: invalid integer " + string(raw))
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: invalid integer " + string(raw))
				}
				n := r.Num()
				if !n.IsUint64() || (bits == 32 && n.Uint64() > 1<<32-1) {
					return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: invalid integer " + string(raw))
				}
				uv = n.Uint64()
			}
		case 5:
			if raw[0] != '"' || !utf8.Valid(raw) {
				return errors.New("proto: opentelemetry.proto.common.v1.InstrumentationScope: invalid string " + string(raw))
			}
			if err := json.Unmarshal(raw, &sv); err != nil {
				return err
			}
		}
		switch jb.f {
		case 0:
			m.Name = sv
		case 1:
			m.Version = sv
		case 2:
			mv := &KeyValue{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Attributes = append(m.Attributes, mv)
		case 3:
			m.DroppedAttributesCount = uint32(uv)
		}
	}
	return nil
}

// A reference to an Entity.
// Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
//
// Status: [Development]
type EntityRef struct {
	// The Schema URL, if known. This is the identifier of the Schema that the entity data
	// is recorded in. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	//
	// This schema_url applies to the data in this message and to the Resource attributes
	// referenced by id_keys and description_keys.
	// TODO: discuss if we are happy with this somewhat complicated definition of what
	// the schema_url applies to.
	//
	// This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
	SchemaUrl string
	// Defines the type of the entity. MUST not change during the lifetime of the entity.
	// For example: "service" or "host". This field is required and MUST not be empty
	// for valid entities.
	Type string
	// Attribute Keys that identify the entity.
	// MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
	// These keys MUST exist in the containing {message}.attributes.
	IdKeys []string
	// Descriptive (non-identifying) attribute keys of the entity.
	// MAY change over the lifetime of the entity. MAY be empty.
	// These attribute keys are not part of entity's identity.
	// These keys MUST exist in the containing {message}.attributes.
	DescriptionKeys []string

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *EntityRef) Reset() { *m = EntityRef{} }

func (m *EntityRef) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

func (m *EntityRef) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntityRef) GetIdKeys() []string {
	if m != nil {
		return m.IdKeys
	}
	return nil
}

func (m *EntityRef) GetDescriptionKeys() []string {
	if m != nil {
		return m.DescriptionKeys
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *EntityRef) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *EntityRef) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.SchemaUrl) > 0 {
		n += 1 + len(m.SchemaUrl) + (bits.Len64((uint64(len(m.SchemaUrl)))|1)+6)/7
	}
	if len(m.Type) > 0 {
		n += 1 + len(m.Type) + (bits.Len64((uint64(len(m.Type)))|1)+6)/7
	}
	for _, v := range m.IdKeys {
		n += 1 + len(v) + (bits.Len64((uint64(len(v)))|1)+6)/7
	}
	for _, v := range m.DescriptionKeys {
		n += 1 + len(v) + (bits.Len64((uint64(len(v)))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *EntityRef) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *EntityRef) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *EntityRef) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for j := len(m.DescriptionKeys) - 1; j >= 0; j-- {
		if !utf8.ValidString(m.DescriptionKeys[j]) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8")
		}
		i -= len(m.DescriptionKeys[j])
		copy(b[i:], m.DescriptionKeys[j])
		u = uint64(len(m.DescriptionKeys[j]))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x22
	}
	for j := len(m.IdKeys) - 1; j >= 0; j-- {
		if !utf8.ValidString(m.IdKeys[j]) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8")
		}
		i -= len(m.IdKeys[j])
		copy(b[i:], m.IdKeys[j])
		u = uint64(len(m.IdKeys[j]))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x1a
	}
	if len(m.Type) > 0 {
		if !utf8.ValidString(m.Type) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8")
		}
		i -= len(m.Type)
		copy(b[i:], m.Type)
		u = uint64(len(m.Type))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x12
	}
	if len(m.SchemaUrl) > 0 {
		if !utf8.ValidString(m.SchemaUrl) {
			return 0, errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8")
		}
		i -= len(m.SchemaUrl)
		copy(b[i:], m.SchemaUrl)
		u = uint64(len(m.SchemaUrl))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x0a
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *EntityRef) UnmarshalBinary(b []byte) error {
	*m = EntityRef{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *EntityRef) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *EntityRef) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8")
				}
				b = b[n:]
				m.SchemaUrl = string(x)
				continue
			}
		case 2:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8")
				}
				b = b[n:]
				m.Type = string(x)
				continue
			}
		case 3:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8")
				}
				b = b[n:]
				m.IdKeys = append(m.IdKeys, string(x))
				continue
			}
		case 4:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8")
				}
				b = b[n:]
				m.DescriptionKeys = append(m.DescriptionKeys, string(x))
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *EntityRef) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *EntityRef) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *EntityRef) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.SchemaUrl) > 0 {
		b = append(b, "\"schemaUrl\":"...)
		if !utf8.ValidString(m.SchemaUrl) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(m.SchemaUrl); ci++ {
			switch c := m.SchemaUrl[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.Type) > 0 {
		b = append(b, "\"type\":"...)
		if !utf8.ValidString(m.Type) {
			return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8")
		}
		b = append(b, '"')
		for ci := 0; ci < len(m.Type); ci++ {
			switch c := m.Type[ci]; {
			case c == '"' || c == '\\':
				b = append(b, '\\', c)
			case c < 0x20:
				b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
			default:
				b = append(b, c)
			}
		}
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.IdKeys) > 0 {
		b = append(b, "\"idKeys\":["...)
		for j := range m.IdKeys {
			if !utf8.ValidString(m.IdKeys[j]) {
				return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8")
			}
			b = append(b, '"')
			for ci := 0; ci < len(m.IdKeys[j]); ci++ {
				switch c := m.IdKeys[j][ci]; {
				case c == '"' || c == '\\':
					b = append(b, '\\', c)
				case c < 0x20:
					b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
				default:
					b = append(b, c)
				}
			}
			b = append(b, '"')
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if len(m.DescriptionKeys) > 0 {
		b = append(b, "\"descriptionKeys\":["...)
		for j := range m.DescriptionKeys {
			if !utf8.ValidString(m.DescriptionKeys[j]) {
				return nil, errors.New("proto: opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8")
			}
			b = append(b, '"')
			for ci := 0; ci < len(m.DescriptionKeys[j]); ci++ {
				switch c := m.DescriptionKeys[j][ci]; {
				case c == '"' || c == '\\':
					b = append(b, '\\', c)
				case c < 0x20:
					b = append(b, '\\', 'u', '0', '0', "0123456789abcdef"[c>>4], "0123456789abcdef"[c&15])
				default:
					b = append(b, c)
				}
			}
			b = append(b, '"')
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *EntityRef) UnmarshalJSON(b []byte) error {
	*m = EntityRef{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *EntityRef) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [4]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "schemaUrl", "schema_url":
			f = 0
		case "type":
			f = 1
		case "idKeys", "id_keys":
			f = 2
		case "descriptionKeys", "description_keys":
			f = 3
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 0, 1:
			if !null {
				jobs = append(jobs, job{f: f, raw: raw})
			}
		case 2, 3:
			if null {
				continue
			}
			ad := json.NewDecoder(bytes.NewReader(raw))
			ad.UseNumber()
			if t, err := ad.Token(); err != nil || t != json.Delim('[') {
				return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: expected a JSON array")
			}
			for ad.More() {
				var e json.RawMessage
				if err := ad.Decode(&e); err != nil {
					return err
				}
				if string(e) == "null" {
					return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: null is not allowed in repeated fields or map values")
				}
				jobs = append(jobs, job{f: f, raw: e})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		class := 0
		var sv string
		switch jb.f {
		case 0, 1, 2, 3:
			class = 5
		}
		switch class {
		case 5:
			if raw[0] != '"' || !utf8.Valid(raw) {
				return errors.New("proto: opentelemetry.proto.common.v1.EntityRef: invalid string " + string(raw))
			}
			if err := json.Unmarshal(raw, &sv); err != nil {
				return err
			}
		}
		switch jb.f {
		case 0:
			m.SchemaUrl = sv
		case 1:
			m.Type = sv
		case 2:
			m.IdKeys = append(m.IdKeys, sv)
		case 3:
			m.DescriptionKeys = append(m.DescriptionKeys, sv)
		}
	}
	return nil
}
