// Code generated by cotorp. DO NOT EDIT.
// source: common/v1/common.proto

package v1

import (
	"cmp"
	"encoding/base64"
	"encoding/binary"
	"encoding/json/jsontext"
	"errors"
	"math"
	"slices"
	"strconv"
	"unicode/utf8"

	pb "./internal/pb"
)

const (
	commonE1 = "proto: field opentelemetry.proto.common.v1.AnyValue.string_value contains invalid UTF-8"
	commonE2 = "proto: field opentelemetry.proto.common.v1.KeyValue.key contains invalid UTF-8"
	commonE3 = "proto: field opentelemetry.proto.common.v1.InstrumentationScope.name contains invalid UTF-8"
	commonE4 = "proto: field opentelemetry.proto.common.v1.InstrumentationScope.version contains invalid UTF-8"
	commonE5 = "proto: field opentelemetry.proto.common.v1.EntityRef.schema_url contains invalid UTF-8"
	commonE6 = "proto: field opentelemetry.proto.common.v1.EntityRef.type contains invalid UTF-8"
	commonE7 = "proto: field opentelemetry.proto.common.v1.EntityRef.description_keys contains invalid UTF-8"
	commonE8 = "proto: field opentelemetry.proto.common.v1.EntityRef.id_keys contains invalid UTF-8"
)

// Represents any type of attribute value. AnyValue may contain a
// primitive value such as a string or integer or it may contain an arbitrary nested
// object containing arrays, key-value lists and primitives.
type AnyValue struct {
	// The value is one of the listed fields. It is valid for all values to be unspecified
	// in which case this AnyValue is considered to be "empty".
	//
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	//	*AnyValue_BytesValue
	//	*AnyValue_StringValueStrindex
	Value isAnyValue_Value

	u []byte
}

// Reset clears all fields of m.
func (m *AnyValue) Reset()                     { *m = AnyValue{} }
func (m *AnyValue) z() *AnyValue               { return pb.If(m == nil, &commonZAnyValue, m) }
func (m *AnyValue) GetValue() isAnyValue_Value { return m.z().Value }
func (m *AnyValue) GetStringValue() string {
	x, _ := m.GetValue().(*AnyValue_StringValue)
	return pb.If(x == nil, new(AnyValue_StringValue), x).StringValue
}
func (m *AnyValue) GetBoolValue() bool {
	x, _ := m.GetValue().(*AnyValue_BoolValue)
	return pb.If(x == nil, new(AnyValue_BoolValue), x).BoolValue
}
func (m *AnyValue) GetIntValue() int64 {
	x, _ := m.GetValue().(*AnyValue_IntValue)
	return pb.If(x == nil, new(AnyValue_IntValue), x).IntValue
}
func (m *AnyValue) GetDoubleValue() float64 {
	x, _ := m.GetValue().(*AnyValue_DoubleValue)
	return pb.If(x == nil, new(AnyValue_DoubleValue), x).DoubleValue
}
func (m *AnyValue) GetArrayValue() *ArrayValue {
	x, _ := m.GetValue().(*AnyValue_ArrayValue)
	return pb.If(x == nil, new(AnyValue_ArrayValue), x).ArrayValue
}
func (m *AnyValue) GetKvlistValue() *KeyValueList {
	x, _ := m.GetValue().(*AnyValue_KvlistValue)
	return pb.If(x == nil, new(AnyValue_KvlistValue), x).KvlistValue
}
func (m *AnyValue) GetBytesValue() []byte {
	x, _ := m.GetValue().(*AnyValue_BytesValue)
	return pb.If(x == nil, new(AnyValue_BytesValue), x).BytesValue
}
func (m *AnyValue) GetStringValueStrindex() int32 {
	x, _ := m.GetValue().(*AnyValue_StringValueStrindex)
	return pb.If(x == nil, new(AnyValue_StringValueStrindex), x).StringValueStrindex
}

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *AnyValue) ProtoUnknownFields() []byte { return m.z().u }

type isAnyValue_Value interface{ isAnyValue_Value() }
type AnyValue_StringValue struct{ StringValue string }
type AnyValue_BoolValue struct{ BoolValue bool }
type AnyValue_IntValue struct{ IntValue int64 }
type AnyValue_DoubleValue struct{ DoubleValue float64 }
type AnyValue_ArrayValue struct{ ArrayValue *ArrayValue }
type AnyValue_KvlistValue struct{ KvlistValue *KeyValueList }
type AnyValue_BytesValue struct{ BytesValue []byte }

// Reference to the string value in ProfilesDictionary.string_table.
//
// Note: This is currently used exclusively in the Profiling signal.
// Implementers of OTLP receivers for signals other than Profiling should
// treat the presence of this value as a non-fatal issue.
// Log an error or warning indicating an unexpected field intended for the
// Profiling signal and process the data as if this value were absent or
// empty, ignoring its semantic content for the non-Profiling signal.
//
// Status: [Alpha]
type AnyValue_StringValueStrindex struct{ StringValueStrindex int32 }

func (*AnyValue_StringValue) isAnyValue_Value()         {}
func (*AnyValue_BoolValue) isAnyValue_Value()           {}
func (*AnyValue_IntValue) isAnyValue_Value()            {}
func (*AnyValue_DoubleValue) isAnyValue_Value()         {}
func (*AnyValue_ArrayValue) isAnyValue_Value()          {}
func (*AnyValue_KvlistValue) isAnyValue_Value()         {}
func (*AnyValue_BytesValue) isAnyValue_Value()          {}
func (*AnyValue_StringValueStrindex) isAnyValue_Value() {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *AnyValue) ProtoSize() (n int) {
	m = m.z()
	switch o := m.Value.(type) {
	case *AnyValue_StringValue:
		n += 1 + pb.SizeLen(len(o.StringValue))
	case *AnyValue_BoolValue:
		n += 1 + 1
	case *AnyValue_IntValue:
		n += 1 + pb.VarintLen(o.IntValue)
	case *AnyValue_DoubleValue:
		n += 1 + pb.Fixed64Size
	case *AnyValue_ArrayValue:
		n += 1 + pb.SizeLen(o.ArrayValue.ProtoSize())
	case *AnyValue_KvlistValue:
		n += 1 + pb.SizeLen(o.KvlistValue.ProtoSize())
	case *AnyValue_BytesValue:
		n += 1 + pb.SizeLen(len(o.BytesValue))
	case *AnyValue_StringValueStrindex:
		n += 1 + pb.VarintLen(o.StringValueStrindex)
	}
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *AnyValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *AnyValue) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *AnyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.GetStringValue(), commonE1, nil); err != nil {
		return 0, err
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		i = pb.PutVarint(b, pb.PutVarint(b, i, uint64(int64(o.StringValueStrindex))), 8<<pb.TagTypeBits|pb.WireVarint)
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		i = pb.PutVarint(b, pb.PutVarint(b, i-copy(b[i-len(o.BytesValue):], o.BytesValue), uint64(len(o.BytesValue))), 7<<pb.TagTypeBits|pb.WireBytes)
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		n, err := o.KvlistValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 6<<pb.TagTypeBits|pb.WireBytes)
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		n, err := o.ArrayValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 5<<pb.TagTypeBits|pb.WireBytes)
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		i = pb.PutVarint(b, pb.PutFixed64(b, i, math.Float64bits(o.DoubleValue)), 4<<pb.TagTypeBits|pb.WireFixed64)
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		i = pb.PutVarint(b, pb.PutVarint(b, i, uint64(o.IntValue)), 3<<pb.TagTypeBits|pb.WireVarint)
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		i = pb.PutVarint(b, pb.PutBool(b, i, o.BoolValue), 2<<pb.TagTypeBits|pb.WireVarint)
	}
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		i = pb.PutVarint(b, pb.PutVarint(b, i-copy(b[i-len(o.StringValue):], o.StringValue), uint64(len(o.StringValue))), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *AnyValue) UnmarshalBinary(b []byte) error { *m = AnyValue{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *AnyValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *AnyValue) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			o := new(AnyValue_StringValue)
			n, err = pb.String(b, &o.StringValue, commonE1)
			m.Value = o
		case 2<<pb.TagTypeBits | pb.WireVarint:
			o := new(AnyValue_BoolValue)
			n, m.Value = pb.Bool(b, &o.BoolValue), o
		case 3<<pb.TagTypeBits | pb.WireVarint:
			o := new(AnyValue_IntValue)
			n, m.Value = pb.Varint(b, &o.IntValue), o
		case 4<<pb.TagTypeBits | pb.WireFixed64:
			o := new(AnyValue_DoubleValue)
			n, m.Value = pb.Double(b, &o.DoubleValue), o
		case 5<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			var mv *ArrayValue
			if o, ok := m.Value.(*AnyValue_ArrayValue); ok && o.ArrayValue != nil {
				mv = o.ArrayValue
			} else {
				mv = &ArrayValue{}
				m.Value = &AnyValue_ArrayValue{ArrayValue: mv}
			}
			err = mv.ProtoMergeDepth(x, depth+1)
		case 6<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			var mv *KeyValueList
			if o, ok := m.Value.(*AnyValue_KvlistValue); ok && o.KvlistValue != nil {
				mv = o.KvlistValue
			} else {
				mv = &KeyValueList{}
				m.Value = &AnyValue_KvlistValue{KvlistValue: mv}
			}
			err = mv.ProtoMergeDepth(x, depth+1)
		case 7<<pb.TagTypeBits | pb.WireBytes:
			o := new(AnyValue_BytesValue)
			n, m.Value = pb.Bytes(b, &o.BytesValue), o
		case 8<<pb.TagTypeBits | pb.WireVarint:
			o := new(AnyValue_StringValueStrindex)
			n, m.Value = pb.Varint(b, &o.StringValueStrindex), o
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *AnyValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *AnyValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *AnyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *AnyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		b, err = pb.Quote(append(b, ",\"stringValue\":"...), o.StringValue, err)
	}
	if o, ok := m.Value.(*AnyValue_BoolValue); ok {
		b = strconv.AppendBool(append(b, ",\"boolValue\":"...), o.BoolValue)
	}
	if o, ok := m.Value.(*AnyValue_IntValue); ok {
		b = append(strconv.AppendInt(append(b, ",\"intValue\":\""...), o.IntValue, 10), '"')
	}
	if o, ok := m.Value.(*AnyValue_DoubleValue); ok {
		b = pb.AppendFloat(append(b, ",\"doubleValue\":"...), o.DoubleValue, 64)
	}
	if o, ok := m.Value.(*AnyValue_ArrayValue); ok {
		b, err = pb.AppendMsg(b, ",\"arrayValue\":", o.ArrayValue, func(v *ArrayValue, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	}
	if o, ok := m.Value.(*AnyValue_KvlistValue); ok {
		b, err = pb.AppendMsg(b, ",\"kvlistValue\":", o.KvlistValue, func(v *KeyValueList, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		b = append(base64.StdEncoding.AppendEncode(append(b, ",\"bytesValue\":\""...), o.BytesValue), '"')
	}
	if o, ok := m.Value.(*AnyValue_StringValueStrindex); ok {
		b = strconv.AppendInt(append(b, ",\"stringValueStrindex\":"...), int64(o.StringValueStrindex), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *AnyValue) UnmarshalJSON(b []byte) error { *m = AnyValue{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *AnyValue) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.AnyValue", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *AnyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = AnyValue{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *AnyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	seen, oneofs := [8]bool{}, [1]bool{}
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.AnyValue"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "stringValue", "string_value":
			o := new(AnyValue_StringValue)
			err = pb.OneofField(d, &seen[0], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.StringValue, false, pb.JSONString)
		case "boolValue", "bool_value":
			o := new(AnyValue_BoolValue)
			err = pb.OneofField(d, &seen[1], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.BoolValue, false, pb.JSONBool)
		case "intValue", "int_value":
			o := new(AnyValue_IntValue)
			err = pb.OneofField(d, &seen[2], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.IntValue, false, pb.JSONInt)
		case "doubleValue", "double_value":
			o := new(AnyValue_DoubleValue)
			err = pb.OneofField(d, &seen[3], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.DoubleValue, false, pb.JSONFloat)
		case "arrayValue", "array_value":
			o := new(AnyValue_ArrayValue)
			err = pb.OneofField(d, &seen[4], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.ArrayValue, false, pb.JSONMsg)
		case "kvlistValue", "kvlist_value":
			o := new(AnyValue_KvlistValue)
			err = pb.OneofField(d, &seen[5], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.KvlistValue, false, pb.JSONMsg)
		case "bytesValue", "bytes_value":
			o := new(AnyValue_BytesValue)
			err = pb.OneofField(d, &seen[6], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.BytesValue, false, pb.JSONBytes)
		case "stringValueStrindex", "string_value_strindex":
			o := new(AnyValue_StringValueStrindex)
			err = pb.OneofField(d, &seen[7], &oneofs[0], key, "opentelemetry.proto.common.v1.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.StringValueStrindex, false, pb.JSONInt)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
// since oneof in AnyValue does not allow repeated fields.
type ArrayValue struct {
	// Array of values. The array may be empty (contain 0 elements).
	Values []*AnyValue

	u []byte
}

// Reset clears all fields of m.
func (m *ArrayValue) Reset()                 { *m = ArrayValue{} }
func (m *ArrayValue) z() *ArrayValue         { return pb.If(m == nil, &commonZArrayValue, m) }
func (m *ArrayValue) GetValues() []*AnyValue { return m.z().Values }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *ArrayValue) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ArrayValue) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsgs(1, m.Values, func(v *AnyValue) int { return v.ProtoSize() })
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ArrayValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *ArrayValue) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *ArrayValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	for _, v := range slices.Backward(m.Values) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *ArrayValue) UnmarshalBinary(b []byte) error {
	*m = ArrayValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *ArrayValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ArrayValue) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Values)).ProtoMergeDepth(x, depth+1)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *ArrayValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ArrayValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *ArrayValue) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *ArrayValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendList(b, ",\"values\":[", m.Values, (*AnyValue).ProtoAppendJSON, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *ArrayValue) UnmarshalJSON(b []byte) error { *m = ArrayValue{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *ArrayValue) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.ArrayValue", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *ArrayValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = ArrayValue{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *ArrayValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [1]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.ArrayValue"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "values":
			err = pb.RepField(d, &seen[0], key, "opentelemetry.proto.common.v1.ArrayValue", &m.Values, false, pb.JSONMsg)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
// since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
// a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
// avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
// are semantically equivalent.
type KeyValueList struct {
	// A collection of key/value pairs of key-value pairs. The list may be empty (may
	// contain 0 elements).
	//
	// The keys MUST be unique (it is not allowed to have more than one
	// value with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Values []*KeyValue

	u []byte
}

// Reset clears all fields of m.
func (m *KeyValueList) Reset()                 { *m = KeyValueList{} }
func (m *KeyValueList) z() *KeyValueList       { return pb.If(m == nil, &commonZKeyValueList, m) }
func (m *KeyValueList) GetValues() []*KeyValue { return m.z().Values }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *KeyValueList) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValueList) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsgs(1, m.Values, func(v *KeyValue) int { return v.ProtoSize() })
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValueList) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValueList) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *KeyValueList) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	for _, v := range slices.Backward(m.Values) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *KeyValueList) UnmarshalBinary(b []byte) error {
	*m = KeyValueList{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *KeyValueList) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValueList) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Values)).ProtoMergeDepth(x, depth+1)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *KeyValueList) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValueList) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *KeyValueList) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *KeyValueList) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendList(b, ",\"values\":[", m.Values, (*KeyValue).ProtoAppendJSON, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *KeyValueList) UnmarshalJSON(b []byte) error { *m = KeyValueList{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *KeyValueList) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.KeyValueList", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *KeyValueList) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = KeyValueList{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *KeyValueList) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [1]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.KeyValueList"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "values":
			err = pb.RepField(d, &seen[0], key, "opentelemetry.proto.common.v1.KeyValueList", &m.Values, false, pb.JSONMsg)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// Represents a key-value pair that is used to store Span attributes, Link
// attributes, etc.
type KeyValue struct {
	// The key name of the pair.
	// key_strindex MUST NOT be set if key is used.
	Key string
	// The value of the pair.
	Value *AnyValue
	// Reference to the string key in ProfilesDictionary.string_table.
	// key MUST NOT be set if key_strindex is used.
	//
	// Note: This is currently used exclusively in the Profiling signal.
	// Implementers of OTLP receivers for signals other than Profiling should
	// treat the presence of this key as a non-fatal issue.
	// Log an error or warning indicating an unexpected field intended for the
	// Profiling signal and process the data as if this value were absent or
	// empty, ignoring its semantic content for the non-Profiling signal.
	//
	// Status: [Alpha]
	KeyStrindex int32

	u []byte
}

// Reset clears all fields of m.
func (m *KeyValue) Reset()                { *m = KeyValue{} }
func (m *KeyValue) z() *KeyValue          { return pb.If(m == nil, &commonZKeyValue, m) }
func (m *KeyValue) GetKey() string        { return m.z().Key }
func (m *KeyValue) GetValue() *AnyValue   { return m.z().Value }
func (m *KeyValue) GetKeyStrindex() int32 { return m.z().KeyStrindex }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *KeyValue) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *KeyValue) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.Key))
	n += pb.SizeMsg(1, m.Value, func(v *AnyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(int64(m.KeyStrindex)))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *KeyValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *KeyValue) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *KeyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Key, commonE2, nil); err != nil {
		return 0, err
	}
	i = pb.PutVarintField(b, i, uint64(int64(m.KeyStrindex)), 3<<pb.TagTypeBits|pb.WireVarint)
	if m.Value != nil {
		n, err := m.Value.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 2<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutStringField(b, i, m.Key, 1<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *KeyValue) UnmarshalBinary(b []byte) error { *m = KeyValue{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *KeyValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *KeyValue) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Key, commonE2)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(&m.Value).ProtoMergeDepth(x, depth+1)
		case 3<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.KeyStrindex)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *KeyValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *KeyValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *KeyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *KeyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.Key) > 0 {
		b, err = pb.Quote(append(b, ",\"key\":"...), m.Key, err)
	}
	b, err = pb.AppendMsg(b, ",\"value\":", m.Value, func(v *AnyValue, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	if m.KeyStrindex != 0 {
		b = strconv.AppendInt(append(b, ",\"keyStrindex\":"...), int64(m.KeyStrindex), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *KeyValue) UnmarshalJSON(b []byte) error { *m = KeyValue{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *KeyValue) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.KeyValue", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *KeyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = KeyValue{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *KeyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [3]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.KeyValue"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "key":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.common.v1.KeyValue", &m.Key, pb.JSONString)
		case "value":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.common.v1.KeyValue", &m.Value, pb.JSONMsg)
		case "keyStrindex", "key_strindex":
			err = pb.Field(d, &seen[2], key, "opentelemetry.proto.common.v1.KeyValue", &m.KeyStrindex, pb.JSONInt)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// InstrumentationScope is a message representing the instrumentation scope information
// such as the fully qualified name and version.
type InstrumentationScope struct {
	// A name denoting the Instrumentation scope.
	// An empty instrumentation scope name means the name is unknown.
	Name string
	// Defines the version of the instrumentation scope.
	// An empty instrumentation scope version means the version is unknown.
	Version string
	// Additional attributes that describe the scope. [Optional].
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*KeyValue
	// The number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32

	u []byte
}

// Reset clears all fields of m.
func (m *InstrumentationScope) Reset() { *m = InstrumentationScope{} }
func (m *InstrumentationScope) z() *InstrumentationScope {
	return pb.If(m == nil, &commonZInstrumentationScope, m)
}
func (m *InstrumentationScope) GetName() string            { return m.z().Name }
func (m *InstrumentationScope) GetVersion() string         { return m.z().Version }
func (m *InstrumentationScope) GetAttributes() []*KeyValue { return m.z().Attributes }
func (m *InstrumentationScope) GetDroppedAttributesCount() uint32 {
	return m.z().DroppedAttributesCount
}

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *InstrumentationScope) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *InstrumentationScope) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.Name))
	n += pb.SizeLenField(1, len(m.Version))
	n += pb.SizeMsgs(1, m.Attributes, func(v *KeyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedAttributesCount))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *InstrumentationScope) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *InstrumentationScope) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *InstrumentationScope) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Version, commonE4, pb.CheckUTF8(m.Name, commonE3, nil)); err != nil {
		return 0, err
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedAttributesCount), 4<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 3<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutStringField(b, i, m.Version, 2<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutStringField(b, i, m.Name, 1<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *InstrumentationScope) UnmarshalBinary(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *InstrumentationScope) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *InstrumentationScope) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Name, commonE3)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Version, commonE4)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Attributes)).ProtoMergeDepth(x, depth+1)
		case 4<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedAttributesCount)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *InstrumentationScope) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *InstrumentationScope) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *InstrumentationScope) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *InstrumentationScope) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.Name) > 0 {
		b, err = pb.Quote(append(b, ",\"name\":"...), m.Name, err)
	}
	if len(m.Version) > 0 {
		b, err = pb.Quote(append(b, ",\"version\":"...), m.Version, err)
	}
	b, err = pb.AppendList(b, ",\"attributes\":[", m.Attributes, (*KeyValue).ProtoAppendJSON, err)
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *InstrumentationScope) UnmarshalJSON(b []byte) error {
	*m = InstrumentationScope{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *InstrumentationScope) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.InstrumentationScope", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *InstrumentationScope) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = InstrumentationScope{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *InstrumentationScope) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [4]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.InstrumentationScope"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "name":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.common.v1.InstrumentationScope", &m.Name, pb.JSONString)
		case "version":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.common.v1.InstrumentationScope", &m.Version, pb.JSONString)
		case "attributes":
			err = pb.RepField(d, &seen[2], key, "opentelemetry.proto.common.v1.InstrumentationScope", &m.Attributes, false, pb.JSONMsg)
		case "droppedAttributesCount", "dropped_attributes_count":
			err = pb.Field(d, &seen[3], key, "opentelemetry.proto.common.v1.InstrumentationScope", &m.DroppedAttributesCount, pb.JSONUint)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// A reference to an Entity.
// Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
//
// Status: [Development]
type EntityRef struct {
	// The Schema URL, if known. This is the identifier of the Schema that the entity data
	// is recorded in. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	//
	// This schema_url applies to the data in this message and to the Resource attributes
	// referenced by id_keys and description_keys.
	// TODO: discuss if we are happy with this somewhat complicated definition of what
	// the schema_url applies to.
	//
	// This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
	SchemaUrl string
	// Defines the type of the entity. MUST not change during the lifetime of the entity.
	// For example: "service" or "host". This field is required and MUST not be empty
	// for valid entities.
	Type string
	// Attribute Keys that identify the entity.
	// MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
	// These keys MUST exist in the containing {message}.attributes.
	IdKeys []string
	// Descriptive (non-identifying) attribute keys of the entity.
	// MAY change over the lifetime of the entity. MAY be empty.
	// These attribute keys are not part of entity's identity.
	// These keys MUST exist in the containing {message}.attributes.
	DescriptionKeys []string

	u []byte
}

// Reset clears all fields of m.
func (m *EntityRef) Reset()                       { *m = EntityRef{} }
func (m *EntityRef) z() *EntityRef                { return pb.If(m == nil, &commonZEntityRef, m) }
func (m *EntityRef) GetSchemaUrl() string         { return m.z().SchemaUrl }
func (m *EntityRef) GetType() string              { return m.z().Type }
func (m *EntityRef) GetIdKeys() []string          { return m.z().IdKeys }
func (m *EntityRef) GetDescriptionKeys() []string { return m.z().DescriptionKeys }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *EntityRef) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *EntityRef) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.SchemaUrl))
	n += pb.SizeLenField(1, len(m.Type))
	n += pb.SizeEach(1, m.IdKeys, pb.BytesLen)
	n += pb.SizeEach(1, m.DescriptionKeys, pb.BytesLen)
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *EntityRef) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *EntityRef) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *EntityRef) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Type, commonE6, pb.CheckUTF8(m.SchemaUrl, commonE5, nil)); err != nil {
		return 0, err
	}
	for _, v := range slices.Backward(m.DescriptionKeys) {
		if !utf8.ValidString(v) {
			return 0, errors.New(commonE7)
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 4<<pb.TagTypeBits|pb.WireBytes)
	}
	for _, v := range slices.Backward(m.IdKeys) {
		if !utf8.ValidString(v) {
			return 0, errors.New(commonE8)
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 3<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutStringField(b, i, m.Type, 2<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutStringField(b, i, m.SchemaUrl, 1<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *EntityRef) UnmarshalBinary(b []byte) error { *m = EntityRef{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *EntityRef) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *EntityRef) ProtoMergeDepth(b []byte, depth int) error {
	err := pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.SchemaUrl, commonE5)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Type, commonE6)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, pb.Grow(&m.IdKeys), commonE8)
		case 4<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, pb.Grow(&m.DescriptionKeys), commonE7)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *EntityRef) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *EntityRef) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *EntityRef) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *EntityRef) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.SchemaUrl) > 0 {
		b, err = pb.Quote(append(b, ",\"schemaUrl\":"...), m.SchemaUrl, err)
	}
	if len(m.Type) > 0 {
		b, err = pb.Quote(append(b, ",\"type\":"...), m.Type, err)
	}
	b, err = pb.AppendList(b, ",\"idKeys\":[", m.IdKeys, func(v string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, v) }, err)
	b, err = pb.AppendList(b, ",\"descriptionKeys\":[", m.DescriptionKeys, func(v string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, v) }, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *EntityRef) UnmarshalJSON(b []byte) error { *m = EntityRef{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *EntityRef) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.common.v1.EntityRef", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *EntityRef) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = EntityRef{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *EntityRef) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [4]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.common.v1.EntityRef"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "schemaUrl", "schema_url":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.common.v1.EntityRef", &m.SchemaUrl, pb.JSONString)
		case "type":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.common.v1.EntityRef", &m.Type, pb.JSONString)
		case "idKeys", "id_keys":
			err = pb.RepField(d, &seen[2], key, "opentelemetry.proto.common.v1.EntityRef", &m.IdKeys, false, pb.JSONString)
		case "descriptionKeys", "description_keys":
			err = pb.RepField(d, &seen[3], key, "opentelemetry.proto.common.v1.EntityRef", &m.DescriptionKeys, false, pb.JSONString)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

var (
	commonZAnyValue             AnyValue
	commonZArrayValue           ArrayValue
	commonZKeyValueList         KeyValueList
	commonZKeyValue             KeyValue
	commonZInstrumentationScope InstrumentationScope
	commonZEntityRef            EntityRef
)
