clients:
  sbom:
      service_url: https://sbom-request.canonical.com
      department: charm_engineering
      email: ben.hoyt@canonical.com
      team: charm_tech
  secscan: {}

artifacts:
  - name: 'pebble'
    type: 'snap'
    ssdlc_params:
        name: 'pebble'
        version: ''  # auto-detect
        channel: 'stable'
