// Code generated by cotorp. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"errors"
	"io"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"

	v11 "github.com/canonical/pebble/internals/otlp/common/v1"
)

// Resource information.
type Resource struct {
	// Set of attributes that describe the resource.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*v11.KeyValue
	// The number of dropped attributes. If the value is 0, then
	// no attributes were dropped.
	DroppedAttributesCount uint32
	// Set of entities that participate in this Resource.
	//
	// Note: keys in the references MUST exist in attributes of this message.
	//
	// Status: [Development]
	EntityRefs []*v11.EntityRef

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Resource) Reset() { *m = Resource{} }

func (m *Resource) GetAttributes() []*v11.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Resource) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Resource) GetEntityRefs() []*v11.EntityRef {
	if m != nil {
		return m.EntityRefs
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Resource) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Resource) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Attributes {
		{
			l := v.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + (bits.Len64((uint64(m.DroppedAttributesCount))|1)+6)/7
	}
	for _, v := range m.EntityRefs {
		{
			l := v.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Resource) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Resource) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Resource) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for j := len(m.EntityRefs) - 1; j >= 0; j-- {
		{
			n, err := m.EntityRefs[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x1a
		}
	}
	if m.DroppedAttributesCount != 0 {
		u = uint64(m.DroppedAttributesCount)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x10
	}
	for j := len(m.Attributes) - 1; j >= 0; j-- {
		{
			n, err := m.Attributes[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x0a
		}
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Resource) UnmarshalBinary(b []byte) error {
	*m = Resource{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Resource) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Resource) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				mv := &v11.KeyValue{}
				m.Attributes = append(m.Attributes, mv)
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 2:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.DroppedAttributesCount = uint32(x)
				continue
			}
		case 3:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				mv := &v11.EntityRef{}
				m.EntityRefs = append(m.EntityRefs, mv)
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Resource) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Resource) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Resource) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Attributes) > 0 {
		b = append(b, "\"attributes\":["...)
		for j := range m.Attributes {
			{
				var err error
				if b, err = m.Attributes[j].ProtoAppendJSON(b); err != nil {
					return nil, err
				}
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if m.DroppedAttributesCount != 0 {
		b = append(b, "\"droppedAttributesCount\":"...)
		b = strconv.AppendUint(b, uint64(m.DroppedAttributesCount), 10)
		b = append(b, ',')
	}
	if len(m.EntityRefs) > 0 {
		b = append(b, "\"entityRefs\":["...)
		for j := range m.EntityRefs {
			{
				var err error
				if b, err = m.EntityRefs[j].ProtoAppendJSON(b); err != nil {
					return nil, err
				}
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Resource) UnmarshalJSON(b []byte) error {
	*m = Resource{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Resource) ProtoMergeJSON(b []byte) error {
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	tok, err := d.Token()
	if err != nil {
		return err
	}
	if tok == nil {
		// JSON null leaves the message unchanged.
		if _, err := d.Token(); err != io.EOF {
			return errors.New("proto: opentelemetry.proto.resource.v1.Resource: unexpected data after JSON value")
		}
		return nil
	}
	if tok != json.Delim('{') {
		return errors.New("proto: opentelemetry.proto.resource.v1.Resource: expected a JSON object")
	}
	type job struct {
		f   int
		key string
		raw []byte
	}
	var jobs []job
	var seen [3]bool
	for d.More() {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		key, _ := tok.(string)
		var raw json.RawMessage
		if err := d.Decode(&raw); err != nil {
			return err
		}
		f := -1
		switch key {
		case "attributes":
			f = 0
		case "droppedAttributesCount", "dropped_attributes_count":
			f = 1
		case "entityRefs", "entity_refs":
			f = 2
		default:
			continue // unknown keys are ignored (-json_discard_unknown)
		}
		if seen[f] {
			return errors.New("proto: opentelemetry.proto.resource.v1.Resource: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		null := string(raw) == "null"
		switch f {
		case 1:
			if !null {
				jobs = append(jobs, job{f: f, raw: raw})
			}
		case 0, 2:
			if null {
				continue
			}
			ad := json.NewDecoder(bytes.NewReader(raw))
			ad.UseNumber()
			if t, err := ad.Token(); err != nil || t != json.Delim('[') {
				return errors.New("proto: opentelemetry.proto.resource.v1.Resource: expected a JSON array")
			}
			for ad.More() {
				var e json.RawMessage
				if err := ad.Decode(&e); err != nil {
					return err
				}
				if string(e) == "null" {
					return errors.New("proto: opentelemetry.proto.resource.v1.Resource: null is not allowed in repeated fields or map values")
				}
				jobs = append(jobs, job{f: f, raw: e})
			}
		}
	}
	if _, err := d.Token(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return errors.New("proto: opentelemetry.proto.resource.v1.Resource: unexpected data after JSON value")
	}
	for _, jb := range jobs {
		raw := jb.raw
		class := 0
		bits := 64
		var uv uint64
		switch jb.f {
		case 1:
			class, bits = 2, 32
		}
		switch class {
		case 2:
			s := string(raw)
			if raw[0] == '"' {
				if err := json.Unmarshal(raw, &s); err != nil {
					return err
				}
			}
			if s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !json.Valid([]byte(s)) {
				return errors.New("proto: opentelemetry.proto.resource.v1.Resource: invalid number " + string(raw))
			}
			var err error
			uv, err = strconv.ParseUint(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > 100 || e < -100 {
						return errors.New("proto: opentelemetry.proto.resource.v1.Resource: invalid integer " + string(raw))
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New("proto: opentelemetry.proto.resource.v1.Resource: invalid integer " + string(raw))
				}
				n := r.Num()
				if !n.IsUint64() || (bits == 32 && n.Uint64() > 1<<32-1) {
					return errors.New("proto: opentelemetry.proto.resource.v1.Resource: invalid integer " + string(raw))
				}
				uv = n.Uint64()
			}
		}
		switch jb.f {
		case 0:
			mv := &v11.KeyValue{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.Attributes = append(m.Attributes, mv)
		case 1:
			m.DroppedAttributesCount = uint32(uv)
		case 2:
			mv := &v11.EntityRef{}
			if err := mv.ProtoMergeJSON(raw); err != nil {
				return err
			}
			m.EntityRefs = append(m.EntityRefs, mv)
		}
	}
	return nil
}
