// Code generated by cotorp. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"errors"
	"slices"
	"strconv"

	v11 "github.com/canonical/pebble/internals/otlp/common/v1"
	pb "github.com/canonical/pebble/internals/otlp/internal/pb"
)

// Resource information.
type Resource struct {
	// Set of attributes that describe the resource.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*v11.KeyValue
	// The number of dropped attributes. If the value is 0, then
	// no attributes were dropped.
	DroppedAttributesCount uint32
	// Set of entities that participate in this Resource.
	//
	// Note: keys in the references MUST exist in attributes of this message.
	//
	// Status: [Development]
	EntityRefs []*v11.EntityRef

	u []byte
}

// Reset clears all fields of m.
func (m *Resource) Reset()                            { *m = Resource{} }
func (m *Resource) z() *Resource                      { return pb.If(m == nil, &resourceZResource, m) }
func (m *Resource) GetAttributes() []*v11.KeyValue    { return m.z().Attributes }
func (m *Resource) GetDroppedAttributesCount() uint32 { return m.z().DroppedAttributesCount }
func (m *Resource) GetEntityRefs() []*v11.EntityRef   { return m.z().EntityRefs }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Resource) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Resource) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsgs(1, m.Attributes, func(v *v11.KeyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedAttributesCount))
	n += pb.SizeMsgs(1, m.EntityRefs, func(v *v11.EntityRef) int { return v.ProtoSize() })
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Resource) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Resource) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Resource) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	for _, v := range slices.Backward(m.EntityRefs) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 3<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedAttributesCount), 2<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Resource) UnmarshalBinary(b []byte) error { *m = Resource{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Resource) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Resource) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Attributes)).ProtoMergeDepth(x, depth+1)
		case 2<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedAttributesCount)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.EntityRefs)).ProtoMergeDepth(x, depth+1)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Resource) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Resource) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Resource) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Resource) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendList(b, ",\"attributes\":[", m.Attributes, (*v11.KeyValue).ProtoAppendJSON, err)
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	b, err = pb.AppendList(b, ",\"entityRefs\":[", m.EntityRefs, (*v11.EntityRef).ProtoAppendJSON, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Resource) UnmarshalJSON(b []byte) error { *m = Resource{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Resource) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.resource.v1.Resource", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Resource) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Resource{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Resource) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [3]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.resource.v1.Resource"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "attributes":
			err = pb.RepField(d, &seen[0], key, "opentelemetry.proto.resource.v1.Resource", &m.Attributes, false, pb.JSONMsg)
		case "droppedAttributesCount", "dropped_attributes_count":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.resource.v1.Resource", &m.DroppedAttributesCount, pb.JSONUint)
		case "entityRefs", "entity_refs":
			err = pb.RepField(d, &seen[2], key, "opentelemetry.proto.resource.v1.Resource", &m.EntityRefs, false, pb.JSONMsg)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

var (
	resourceZResource Resource
)
