// Code generated by cotorp. DO NOT EDIT.
// helpers: shared by the packages generated with -helpers

// Package pb holds the helper functions and constants of the code that
// cotorp generates with -helpers. It has no stable API.
package pb

import (
	"bytes"
	"cmp"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	// Wire types.
	WireVarint     = 0
	WireFixed64    = 1
	WireBytes      = 2
	WireStartGroup = 3
	WireEndGroup   = 4
	WireFixed32    = 5
	// A tag holds the field number above the wire type in its low three bits.
	TagTypeBits    = 3
	TagTypeMask    = 1<<3 - 1
	MaxFieldNumber = 1<<29 - 1
	// Map entries are encoded as messages with these field numbers.
	MapKeyField   = 1
	MapValueField = 2
	// Encoded sizes.
	Fixed32Size       = 4
	Fixed64Size       = 8
	VarintPayloadBits = 7
	VarintContBit     = 0x80
	// Decoding limits.
	MaxDepth = 10000
	// ProtoJSON limits.
	MaxJSONExponent     = 100
	Base64Quantum       = 4
	MaxFracDigits       = 9
	MinTimestampSeconds = -62135596800
	MaxTimestampSeconds = 253402300799
	MaxDurationSeconds  = 315576000000
	// Time units.
	NanosPerSecond  = 1000000000
	NanosPerMilli   = 1000000
	NanosPerMicro   = 1000
	MicrosPerSecond = 1000000
	MillisPerSecond = 1000
	// Error messages.
	ErrSizeChanged    = "proto: message size changed during marshal"
	ErrDepth          = "proto: exceeded maximum recursion depth"
	ErrParse          = "proto: cannot parse invalid wire-format data"
	ErrTrailingData   = "unexpected data after JSON value"
	ErrExpected       = "expected a JSON "
	ErrDuplicateField = "duplicate field "
	ErrOneofConflict  = "multiple fields set for oneof "
	ErrNullElement    = "null is not allowed in repeated fields or map values"
	ErrInvalidBool    = "invalid boolean "
	ErrInvalidString  = "invalid string "
	ErrInvalidBytes   = "invalid bytes "
	ErrInvalidHex     = "invalid hex bytes "
	ErrInvalidEnum    = "invalid value for enum "
	ErrInvalidInteger = "invalid integer "
	ErrInvalidNumber  = "invalid number "
	ErrInvalidKey     = "invalid map key for field "
)

// SizeLen returns the encoded size of a length-delimited value of l bytes: the length prefix plus l.
func SizeLen(l int) int { return l + VarintLen(l) }

// SizeVarint returns the size of an implicit-presence varint field u with a tag of tag bytes, or 0 if u is zero.
func SizeVarint(tag int, u uint64) int { return If(u == 0, 0, tag+VarintLen(u)) }

// SizeBool returns the size of an implicit-presence bool field, or 0 if v is false.
func SizeBool(tag int, v bool) int { return If(v, tag+1, 0) }

// SizeFixed returns tag+size, the size of a fixed-width field, if set, or 0.
func SizeFixed(tag, size int, set bool) int { return If(set, tag+size, 0) }

// SizeLenField returns the size of an implicit-presence string, bytes or packed field of l bytes, or 0 if l is zero.
func SizeLenField(tag, l int) int { return If(l == 0, 0, tag+SizeLen(l)) }

// SizePresentBytes returns the size of an explicit-presence bytes field, or 0 if v is nil.
func SizePresentBytes(tag int, v []byte) int { return If(v == nil, 0, tag+SizeLen(len(v))) }

// SizeMsg returns the size of message field p, measured by size, or 0 if p is nil.
func SizeMsg[T any](tag int, p *T, size func(*T) int) int {
	if p == nil {
		return 0
	}
	return tag + SizeLen(size(p))
}

// SizeMsgs returns the size of repeated message field s, whose elements are measured by size.
func SizeMsgs[T any](tag int, s []*T, size func(*T) int) (n int) {
	for _, v := range s {
		n += tag + SizeLen(size(v))
	}
	return n
}

// SizeOpt returns the size of explicit-presence field p, measured by size, or 0 if p is nil.
func SizeOpt[T any](tag int, p *T, size func(T) int) int {
	if p == nil {
		return 0
	}
	return tag + size(*p)
}

// SizeOptFixed returns tag+size for explicit-presence fixed-width field p, or 0 if p is nil.
func SizeOptFixed[T any](tag, size int, p *T) int { return If(p == nil, 0, tag+size) }

// SizePacked returns the size of packed field s, whose elements are measured by size, or 0 if s is empty.
func SizePacked[T any](tag int, s []T, size func(T) int) int {
	if len(s) == 0 {
		return 0
	}
	l := 0
	for _, v := range s {
		l += size(v)
	}
	return tag + SizeLen(l)
}

// SizeEach returns the size of repeated field s, whose elements are measured by size and each carry a tag.
func SizeEach[T any](tag int, s []T, size func(T) int) (n int) {
	for _, v := range s {
		n += tag + size(v)
	}
	return n
}

// VarintLen returns the number of bytes in the varint encoding of v.
func VarintLen[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](v T) int {
	return (bits.Len64(uint64(int64(v))|1) + VarintPayloadBits - 1) / VarintPayloadBits
}

// Sint32Len returns the number of bytes in the zigzag varint encoding of v.
func Sint32Len(v int32) int {
	return (bits.Len64(uint64(uint32((v)<<1)^uint32((v)>>31))|1) + VarintPayloadBits - 1) / VarintPayloadBits
}

// Sint64Len returns the number of bytes in the zigzag varint encoding of v.
func Sint64Len(v int64) int {
	return (bits.Len64((uint64((v)<<1)^uint64((v)>>63))|1) + VarintPayloadBits - 1) / VarintPayloadBits
}

// BoolLen returns the size of an encoded bool, which is 1.
func BoolLen(bool) int { return 1 }

// BytesLen returns the size of length-delimited value v with its length prefix.
func BytesLen[T ~string | ~[]byte](v T) int { return SizeLen(len(v)) }

// CheckUTF8 returns an error with message msg if s is not valid UTF-8, and err otherwise.
func CheckUTF8(s, msg string, err error) error {
	if len(s) > 0 && !utf8.ValidString(s) {
		return errors.New(msg)
	}
	return err
}

// CopyUnknown copies the unknown fields u to the end of b[:i] and returns the new i.
func CopyUnknown(b []byte, i int, u []byte) int {
	if len(u) > 0 {
		i -= copy(b[i-len(u):], u)
	}
	return i
}

// AppendBinary grows b by size, marshals into the new space with marshal and returns the result, or an error if marshal fails or writes another count.
func AppendBinary(b []byte, size int, marshal func([]byte) (int, error)) ([]byte, error) {
	b = slices.Grow(b, size)
	n, err := marshal(b[len(b) : len(b)+size])
	if err == nil && n != size {
		err = errors.New(ErrSizeChanged)
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}

// PutVarint writes varint u ending at b[i] and returns the new i.
func PutVarint(b []byte, i int, u uint64) int {
	if u < VarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + VarintPayloadBits - 1) / VarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}

// PutFixed32 writes u as four little-endian bytes ending at b[i] and returns the new i.
func PutFixed32(b []byte, i int, u uint32) int {
	binary.LittleEndian.PutUint32(b[i-Fixed32Size:], u)
	return i - Fixed32Size
}

// PutFixed64 writes u as eight little-endian bytes ending at b[i] and returns the new i.
func PutFixed64(b []byte, i int, u uint64) int {
	binary.LittleEndian.PutUint64(b[i-Fixed64Size:], u)
	return i - Fixed64Size
}

// PutBool writes v as one byte at b[i-1] and returns the new i.
func PutBool(b []byte, i int, v bool) int {
	b[i-1] = 0
	if v {
		b[i-1] = 1
	}
	return i - 1
}

// PutVarintField writes varint field u with its one-byte tag ending at b[i] and returns the new i, or i if u is zero.
func PutVarintField(b []byte, i int, u uint64, tag byte) int {
	if u == 0 {
		return i
	}
	i -= (bits.Len64(u|1)+VarintPayloadBits-1)/VarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= VarintContBit; u >>= VarintPayloadBits {
		b[p] = byte(u) | VarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}

// PutStringField writes string field v with its length and one-byte tag ending at b[i] and returns the new i, or i if v is empty.
func PutStringField(b []byte, i int, v string, tag byte) int {
	if len(v) == 0 {
		return i
	}
	i -= copy(b[i-len(v):], v)
	u := uint64(len(v))
	i -= (bits.Len64(u|1)+VarintPayloadBits-1)/VarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= VarintContBit; u >>= VarintPayloadBits {
		b[p] = byte(u) | VarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}

// PutBytesField writes bytes field v with its length and one-byte tag ending at b[i] and returns the new i, or i if v is empty.
func PutBytesField(b []byte, i int, v []byte, tag byte) int {
	if len(v) == 0 {
		return i
	}
	i -= copy(b[i-len(v):], v)
	u := uint64(len(v))
	i -= (bits.Len64(u|1)+VarintPayloadBits-1)/VarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= VarintContBit; u >>= VarintPayloadBits {
		b[p] = byte(u) | VarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}

// PutFixed32Field writes fixed32 field u with its one-byte tag ending at b[i] and returns the new i, or i if u is zero.
func PutFixed32Field(b []byte, i int, u uint32, tag byte) int {
	if u == 0 {
		return i
	}
	binary.LittleEndian.PutUint32(b[i-Fixed32Size:], u)
	i -= Fixed32Size + 1
	b[i] = tag
	return i
}

// PutFixed64Field writes fixed64 field u with its one-byte tag ending at b[i] and returns the new i, or i if u is zero.
func PutFixed64Field(b []byte, i int, u uint64, tag byte) int {
	if u == 0 {
		return i
	}
	binary.LittleEndian.PutUint64(b[i-Fixed64Size:], u)
	i -= Fixed64Size + 1
	b[i] = tag
	return i
}

// PutBoolField writes bool field v with its one-byte tag ending at b[i] and returns the new i, or i if v is false.
func PutBoolField(b []byte, i int, v bool, tag byte) int {
	if !v {
		return i
	}
	i -= 2
	b[i] = tag
	b[i+1] = 1
	return i
}

// PutVarintField2 is PutVarintField with a two-byte tag.
func PutVarintField2(b []byte, i int, u uint64, tag uint16) int {
	if u == 0 {
		return i
	}
	i -= (bits.Len64(u|1)+VarintPayloadBits-1)/VarintPayloadBits + 2
	b[i], b[i+1] = byte(tag)|VarintContBit, byte(tag>>VarintPayloadBits)
	p := i + 2
	for ; u >= VarintContBit; u >>= VarintPayloadBits {
		b[p] = byte(u) | VarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}

// PutFixed32Field2 is PutFixed32Field with a two-byte tag.
func PutFixed32Field2(b []byte, i int, u uint32, tag uint16) int {
	if u == 0 {
		return i
	}
	binary.LittleEndian.PutUint32(b[i-Fixed32Size:], u)
	i -= Fixed32Size + 2
	b[i], b[i+1] = byte(tag)|VarintContBit, byte(tag>>VarintPayloadBits)
	return i
}

// PutFixed64Field2 is PutFixed64Field with a two-byte tag.
func PutFixed64Field2(b []byte, i int, u uint64, tag uint16) int {
	if u == 0 {
		return i
	}
	binary.LittleEndian.PutUint64(b[i-Fixed64Size:], u)
	i -= Fixed64Size + 2
	b[i], b[i+1] = byte(tag)|VarintContBit, byte(tag>>VarintPayloadBits)
	return i
}

// PutBoolField2 is PutBoolField with a two-byte tag.
func PutBoolField2(b []byte, i int, v bool, tag uint16) int {
	if !v {
		return i
	}
	i -= 3
	b[i], b[i+1] = byte(tag)|VarintContBit, byte(tag>>VarintPayloadBits)
	b[i+2] = 1
	return i
}

// SortedKeys appends the keys of m to keys and sorts them.
func SortedKeys[K cmp.Ordered, V any](m map[K]V, keys []K) []K {
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// If returns a if c, and b otherwise. Both are evaluated.
func If[T any](c bool, a, b T) T {
	if c {
		return a
	}
	return b
}

// Depth returns an error if depth reaches the nesting limit.
func Depth(depth int) error {
	if depth >= MaxDepth {
		return errors.New(ErrDepth)
	}
	return nil
}

// ReadBytes returns the length-delimited value at the start of b and the number of bytes it occupies, or -1 if it is malformed.
func ReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}

// SkipField returns the length of the value of the field with tag t at b, or an error if it is malformed.
func SkipField(b []byte, t uint64, depth int) (int, error) {
	n, num := 0, t>>TagTypeBits
	switch wt := t & TagTypeMask; {
	case num == 0 || num > MaxFieldNumber:
	case wt == WireVarint:
		_, n = binary.Uvarint(b)
	case wt == WireBytes:
		_, n = ReadBytes(b)
	case wt == WireStartGroup:
		return SkipGroup(b, int32(num), depth+1)
	case wt == WireFixed64 || wt == WireFixed32:
		n = If(wt == WireFixed64, Fixed64Size, Fixed32Size)
		n = If(len(b) >= n, n, 0)
	}
	if n <= 0 {
		return 0, errors.New(ErrParse)
	}
	return n, nil
}

// SkipGroup returns the length of the group with field number num at b, up to and including its end tag.
func SkipGroup(b []byte, num int32, depth int) (int, error) {
	n, err := 0, Depth(depth)
	for err == nil {
		t, k := binary.Uvarint(b[n:])
		if k <= 0 {
			return 0, errors.New(ErrParse)
		}
		if n += k; t == uint64(num)<<TagTypeBits|WireEndGroup {
			return n, nil
		}
		k, err = SkipField(b[n:], t, depth)
		n += k
	}
	return 0, err
}

// Unknown skips the field with tag t at b and appends it, with a canonical tag, to *unk.
func Unknown(b []byte, t uint64, depth int, unk *[]byte) (int, error) {
	n, err := SkipField(b, t, depth)
	if err == nil {
		*unk = append(binary.AppendUvarint(*unk, t), b[:n]...)
	}
	return n, err
}

// End returns err, or a parse error if b is not empty.
func End(b []byte, err error) error {
	if err == nil && len(b) > 0 {
		return errors.New(ErrParse)
	}
	return err
}

// Varint decodes the varint at b into *p and returns the number of bytes consumed, or 0 or less if it is malformed.
func Varint[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](b []byte, p *T) int {
	u, n := binary.Uvarint(b)
	*p = T(u)
	return n
}

// Sint32 decodes the zigzag varint at b into *p and returns the number of bytes consumed, or 0 or less if it is malformed.
func Sint32(b []byte, p *int32) int {
	u, n := binary.Uvarint(b)
	*p = int32(uint32(u)>>1) ^ -int32(u&1)
	return n
}

// Sint64 decodes the zigzag varint at b into *p and returns the number of bytes consumed, or 0 or less if it is malformed.
func Sint64(b []byte, p *int64) int {
	u, n := binary.Uvarint(b)
	*p = int64(u>>1) ^ -int64(u&1)
	return n
}

// Bool decodes the varint at b as a bool into *p and returns the number of bytes consumed, or 0 or less if it is malformed.
func Bool(b []byte, p *bool) int { u, n := binary.Uvarint(b); *p = u != 0; return n }

// Fixed32 decodes the four little-endian bytes at b into *p and returns 4, or -1 if b is shorter.
func Fixed32[T ~uint32 | ~int32](b []byte, p *T) int {
	if len(b) < Fixed32Size {
		return -1
	}
	*p = T(binary.LittleEndian.Uint32(b))
	return Fixed32Size
}

// Fixed64 decodes the eight little-endian bytes at b into *p and returns 8, or -1 if b is shorter.
func Fixed64[T ~uint64 | ~int64](b []byte, p *T) int {
	if len(b) < Fixed64Size {
		return -1
	}
	*p = T(binary.LittleEndian.Uint64(b))
	return Fixed64Size
}

// Float decodes the four little-endian bytes at b as a float32 into *p and returns 4, or -1 if b is shorter.
func Float(b []byte, p *float32) int {
	if len(b) < Fixed32Size {
		return -1
	}
	*p = math.Float32frombits(binary.LittleEndian.Uint32(b))
	return Fixed32Size
}

// Double decodes the eight little-endian bytes at b as a float64 into *p and returns 8, or -1 if b is shorter.
func Double(b []byte, p *float64) int {
	if len(b) < Fixed64Size {
		return -1
	}
	*p = math.Float64frombits(binary.LittleEndian.Uint64(b))
	return Fixed64Size
}

// Bytes decodes the length-delimited value at b into a copy at *p and returns the number of bytes consumed, or -1 if it is malformed.
func Bytes(b []byte, p *[]byte) int {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return -1
	}
	*p = append([]byte{}, b[k:k+int(ln)]...)
	return k + int(ln)
}

// String decodes the length-delimited value at b into *p and returns the number of bytes consumed, or -1 if it is malformed; with errUTF8 set, invalid UTF-8 is an error with that message.
func String(b []byte, p *string, errUTF8 string) (int, error) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return -1, nil
	}
	x := b[k : k+int(ln)]
	if errUTF8 != "" && !utf8.Valid(x) {
		return 0, errors.New(errUTF8)
	}
	*p = string(x)
	return k + int(ln), nil
}

// PackedVarint appends the elements of the packed varint field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedVarint[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](b []byte, s *[]T) int {
	x, n := ReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		u, k := binary.Uvarint(x)
		if k <= 0 {
			return -1
		}
		x, *s = x[k:], append(*s, T(u))
	}
	return n
}

// PackedSint32 appends the elements of the packed sint32 field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedSint32(b []byte, s *[]int32) int {
	x, n := ReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		u, k := binary.Uvarint(x)
		if k <= 0 {
			return -1
		}
		x, *s = x[k:], append(*s, int32(uint32(u)>>1)^-int32(u&1))
	}
	return n
}

// PackedSint64 appends the elements of the packed sint64 field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedSint64(b []byte, s *[]int64) int {
	x, n := ReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		u, k := binary.Uvarint(x)
		if k <= 0 {
			return -1
		}
		x, *s = x[k:], append(*s, int64(u>>1)^-int64(u&1))
	}
	return n
}

// PackedBool appends the elements of the packed bool field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedBool(b []byte, s *[]bool) int {
	x, n := ReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		u, k := binary.Uvarint(x)
		if k <= 0 {
			return -1
		}
		x, *s = x[k:], append(*s, u != 0)
	}
	return n
}

// PackedFixed32 appends the elements of the packed fixed32 field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedFixed32[T ~uint32 | ~int32](b []byte, s *[]T) int {
	x, n := ReadBytes(b)
	if n < 0 || len(x)%Fixed32Size != 0 {
		return -1
	}
	if *s == nil {
		*s = make([]T, 0, len(x)/Fixed32Size)
	}
	for ; len(x) > 0; x = x[Fixed32Size:] {
		*s = append(*s, T(binary.LittleEndian.Uint32(x)))
	}
	return n
}

// PackedFixed64 appends the elements of the packed fixed64 field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedFixed64[T ~uint64 | ~int64](b []byte, s *[]T) int {
	x, n := ReadBytes(b)
	if n < 0 || len(x)%Fixed64Size != 0 {
		return -1
	}
	if *s == nil {
		*s = make([]T, 0, len(x)/Fixed64Size)
	}
	for ; len(x) > 0; x = x[Fixed64Size:] {
		*s = append(*s, T(binary.LittleEndian.Uint64(x)))
	}
	return n
}

// PackedFloat appends the elements of the packed float field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedFloat(b []byte, s *[]float32) int {
	x, n := ReadBytes(b)
	if n < 0 || len(x)%Fixed32Size != 0 {
		return -1
	}
	if *s == nil {
		*s = make([]float32, 0, len(x)/Fixed32Size)
	}
	for ; len(x) > 0; x = x[Fixed32Size:] {
		*s = append(*s, math.Float32frombits(binary.LittleEndian.Uint32(x)))
	}
	return n
}

// PackedDouble appends the elements of the packed double field at b to *s and returns the number of bytes consumed, or -1 if it is malformed.
func PackedDouble(b []byte, s *[]float64) int {
	x, n := ReadBytes(b)
	if n < 0 || len(x)%Fixed64Size != 0 {
		return -1
	}
	if *s == nil {
		*s = make([]float64, 0, len(x)/Fixed64Size)
	}
	for ; len(x) > 0; x = x[Fixed64Size:] {
		*s = append(*s, math.Float64frombits(binary.LittleEndian.Uint64(x)))
	}
	return n
}

// ClosedEnum decodes the varint at b as a closed enum value and calls set with it if it is declared, or keeps it in *unk as an unknown field with tag; it returns the number of bytes consumed, or -1 if it is malformed.
func ClosedEnum[E interface {
	~int32
	IsValid() bool
}](b []byte, unk *[]byte, tag uint64, set func(E)) int {
	u, n := binary.Uvarint(b)
	if n <= 0 {
		return -1
	}
	if e := E(u); e.IsValid() {
		set(e)
	} else {
		*unk = append(binary.AppendUvarint(*unk, tag), b[:n]...)
	}
	return n
}

// PackedClosedEnum is ClosedEnum for the elements of a packed field.
func PackedClosedEnum[E interface {
	~int32
	IsValid() bool
}](b []byte, unk *[]byte, tag uint64, set func(E)) int {
	x, n := ReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		k := ClosedEnum(x, unk, tag, set)
		if k <= 0 {
			return -1
		}
		x = x[k:]
	}
	return n
}

// Group returns the contents of the group with field number num at b, without its end tag, and the length of the whole group.
func Group(b []byte, num int32, depth int) ([]byte, int, error) {
	n, err := SkipGroup(b, num, depth)
	if err != nil {
		return nil, 0, err
	}
	return b[:n-(bits.Len64(uint64(num)<<TagTypeBits|WireEndGroup|1)+VarintPayloadBits-1)/VarintPayloadBits], n, nil
}

// New allocates *p and returns it.
func New[T any](p **T) *T { *p = new(T); return *p }

// Grow appends a zero element to *s and returns a pointer to it.
func Grow[T any](s *[]T) *T { var z T; *s = append(*s, z); return &(*s)[len(*s)-1] }

// Alloc allocates *p if it is nil and returns it.
func Alloc[T any](p **T) *T {
	if *p == nil {
		*p = new(T)
	}
	return *p
}

// MapSet stores v under k in *m, allocating the map if it is nil.
func MapSet[K comparable, V any](m *map[K]V, k K, v V) {
	if *m == nil {
		*m = make(map[K]V)
	}
	(*m)[k] = v
}

// Invert returns the map from m's values to its keys.
func Invert[K, V comparable](m map[K]V) map[V]K {
	r := make(map[V]K, len(m))
	for k, v := range m {
		r[v] = k
	}
	return r
}

// EnumString returns the name of enum value v in names, or its number.
func EnumString(names map[int32]string, v int32) string {
	if s, ok := names[v]; ok {
		return s
	}
	return strconv.Itoa(int(v))
}

// Deref returns *p, or def if p is nil.
func Deref[T any](p *T, def T) T {
	if p != nil {
		return *p
	}
	return def
}

// BytesOr returns v, or a copy of def if v is nil.
func BytesOr(v, def []byte) []byte {
	if v != nil {
		return v
	}
	return append([]byte(nil), def...)
}

// MarshalTo writes the JSON value appended by f to e.
func MarshalTo(e *jsontext.Encoder, f func([]byte) ([]byte, error)) error {
	b, err := f(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// AppendEnum appends the name of enum value v in names as a JSON string, or its number.
func AppendEnum(b []byte, v int32, names map[int32]string) []byte {
	if s, ok := names[v]; ok {
		b = append(b, '"')
		b = append(b, s...)
		return append(b, '"')
	}
	return strconv.AppendInt(b, int64(v), 10)
}

// AppendFloat appends f as a JSON number, or as the string NaN, Infinity or -Infinity.
func AppendFloat(b []byte, f float64, bits int) []byte {
	switch {
	case math.IsNaN(f):
		return append(b, `"NaN"`...)
	case math.IsInf(f, 1):
		return append(b, `"Infinity"`...)
	case math.IsInf(f, -1):
		return append(b, `"-Infinity"`...)
	}
	return jsontext.AppendFloat(b, f, bits)
}

// Quote appends s as a JSON string, or nothing if err is set.
func Quote(b []byte, s string, err error) ([]byte, error) {
	if err != nil {
		return b, err
	}
	return jsontext.AppendQuote(b, s)
}

// AppendMsg appends lit and then the JSON encoding of message p by f, or nothing if p is nil or err is set.
func AppendMsg[T any](b []byte, lit string, p *T, f func(*T, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || p == nil {
		return b, err
	}
	return f(p, append(b, lit...))
}

// AppendList appends lit, which ends with the opening bracket, and the JSON array of the elements of s encoded by f, or nothing if s is empty or err is set.
func AppendList[T any](b []byte, lit string, s []T, f func(T, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || len(s) == 0 {
		return b, err
	}
	b = append(b, lit...)
	for _, v := range s {
		if b, err = f(v, b); err != nil {
			return b, err
		}
		b = append(b, ',')
	}
	b[len(b)-1] = ']'
	return b, nil
}

// AppendMap appends lit, which ends with the opening brace, and the JSON object of the entries of m in key order, encoded by fk and fv, or nothing if m is empty or err is set.
func AppendMap[K cmp.Ordered, V any](b []byte, lit string, m map[K]V, fk func(K, []byte) ([]byte, error), fv func(V, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || len(m) == 0 {
		return b, err
	}
	b = append(b, lit...)
	for _, k := range SortedKeys(m, make([]K, 0, len(m))) {
		if b, err = fk(k, b); err != nil {
			return b, err
		}
		if b, err = fv(m[k], append(b, ':')); err != nil {
			return b, err
		}
		b = append(b, ',')
	}
	b[len(b)-1] = '}'
	return b, nil
}

// CloseObject closes the JSON object started at b[start], whose members each begin with a comma, or appends {} if it has none.
func CloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}

// MergeJSON decodes the JSON value in b with merge and rejects trailing data.
func MergeJSON(b []byte, name string, merge func(*jsontext.Decoder) error) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := merge(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return JSONError(name, ErrTrailingData)
	}
	return nil
}

// MergeFrom decodes a JSON value from d with merge, or from a strict copy of the value if d allows invalid UTF-8.
func MergeFrom(d *jsontext.Decoder, merge func(*jsontext.Decoder) error) error {
	d, err := StrictDecoder(d)
	return cmp.Or(err, merge(d))
}

// StrictDecoder returns d, or a decoder over its next value that rejects invalid UTF-8 if d does not.
func StrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return d, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}

// ExpectJSON reads a token from d, which must be of the given kind.
func ExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return JSONError(name, ErrExpected+what)
	}
	return nil
}

// OpenObject reads the opening brace of the JSON object of message name and returns its first key, or EndObject for an empty object or null.
func OpenObject(d *jsontext.Decoder, name string) (jsontext.Token, error) {
	if d.PeekKind() == jsontext.KindNull {
		return jsontext.EndObject, d.SkipValue()
	}
	return NextKey(d, ExpectJSON(d, jsontext.KindBeginObject, name, "object"))
}

// NextKey returns the next key of a JSON object, or its closing brace, unless err is set.
func NextKey(d *jsontext.Decoder, err error) (jsontext.Token, error) {
	if err != nil {
		return jsontext.Token{}, err
	}
	return d.ReadToken()
}

// Field parses the value of field key into p, rejecting a duplicate key.
func Field[T any](d *jsontext.Decoder, seen *bool, key, name string, p *T, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return JSONError(name, ErrDuplicateField+strconv.Quote(key))
	}
	*seen = true
	return parse(d, p, name)
}

// OptField parses the value of explicit-presence field key into a new *p, or leaves it on null.
func OptField[T any](d *jsontext.Decoder, seen *bool, key, name string, p **T, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return JSONError(name, ErrDuplicateField+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return parse(d, New(p), name)
}

// RepField parses the JSON array of repeated field key into s, or leaves it on null.
func RepField[T any](d *jsontext.Decoder, seen *bool, key, name string, s *[]T, nullOK bool, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return JSONError(name, ErrDuplicateField+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return JSONArray(d, s, name, nullOK, parse)
}

// MapField parses the JSON object of map field key into m, with pk parsing keys and pv values, or leaves it on null.
func MapField[K comparable, V any](d *jsontext.Decoder, seen *bool, key, name, field string, m *map[K]V, nullOK bool, pk func(string, string, string) (K, error), pv func(*jsontext.Decoder, *V, string) error) error {
	if *seen {
		return JSONError(name, ErrDuplicateField+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return JSONMap(d, m, name, field, nullOK, pk, pv)
}

// OneofField stores wrapper w in oneof field p and parses the value of field key into w's field v, rejecting a second member; null leaves p unless nullOK.
func OneofField[I, T any](d *jsontext.Decoder, seen, oneof *bool, key, name, oneofName string, p *I, w I, v *T, nullOK bool, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return JSONError(name, ErrDuplicateField+strconv.Quote(key))
	}
	*seen = true
	if !nullOK && d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	if *oneof {
		return JSONError(name, ErrOneofConflict+oneofName)
	}
	*oneof, *p = true, w
	return parse(d, v, name)
}

// JSONArray parses a JSON array, appending each element parsed by parse to *s; null elements are rejected unless nullOK.
func JSONArray[T any](d *jsontext.Decoder, s *[]T, name string, nullOK bool, parse func(*jsontext.Decoder, *T, string) error) error {
	if err := ExpectJSON(d, jsontext.KindBeginArray, name, "array"); err != nil {
		return err
	}
	for d.PeekKind() != jsontext.KindEndArray {
		if !nullOK && d.PeekKind() == jsontext.KindNull {
			return JSONError(name, ErrNullElement)
		}
		if err := parse(d, Grow(s), name); err != nil {
			return err
		}
	}
	_, err := d.ReadToken()
	return err
}

// JSONMap parses a JSON object into *m, with pk parsing keys and pv values; null values are rejected unless nullOK.
func JSONMap[K comparable, V any](d *jsontext.Decoder, m *map[K]V, name, field string, nullOK bool, pk func(string, string, string) (K, error), pv func(*jsontext.Decoder, *V, string) error) error {
	if err := ExpectJSON(d, jsontext.KindBeginObject, name, "object"); err != nil {
		return err
	}
	for d.PeekKind() != jsontext.KindEndObject {
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		k, err := pk(kt.String(), name, field)
		if err != nil {
			return err
		}
		if !nullOK && d.PeekKind() == jsontext.KindNull {
			return JSONError(name, ErrNullElement)
		}
		var v V
		if err := pv(d, &v, name); err != nil {
			return err
		}
		MapSet(m, k, v)
	}
	_, err := d.ReadToken()
	return err
}

// JSONInt parses a JSON integer, as a number or a string, into *p, or leaves it on null.
func JSONInt[T ~int32 | ~int64](d *jsontext.Decoder, p *T, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	bits := 64
	if T(1)<<31 < 0 {
		bits = 32
	}
	v, err := ParseInt(tok, bits, name)
	*p = T(v)
	return err
}

// JSONUint parses a JSON unsigned integer, as a number or a string, into *p, or leaves it on null.
func JSONUint[T ~uint32 | ~uint64](d *jsontext.Decoder, p *T, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	bits := 64
	if ^T(0)>>31 == 1 {
		bits = 32
	}
	v, err := ParseUint(tok, bits, name)
	*p = T(v)
	return err
}

// JSONFloat parses a JSON number, or a string holding a number, NaN, Infinity or -Infinity, into *p, or leaves it on null.
func JSONFloat[T ~float32 | ~float64](d *jsontext.Decoder, p *T, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	bits := 64
	if float64(T(1)/T(3)) != 1.0/3 {
		bits = 32
	}
	v, err := ParseFloat(tok, bits, name)
	*p = T(v)
	return err
}

// JSONBool parses a JSON boolean into *p, or leaves it on null.
func JSONBool(d *jsontext.Decoder, p *bool, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	switch tok.Kind() {
	case jsontext.KindTrue:
		*p = true
	case jsontext.KindFalse:
		*p = false
	default:
		return JSONError(name, ErrInvalidBool+tok.String())
	}
	return nil
}

// JSONString parses a JSON string into *p, or leaves it on null.
func JSONString(d *jsontext.Decoder, p *string, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	if tok.Kind() != jsontext.KindString {
		return JSONError(name, ErrInvalidString+tok.String())
	}
	*p = tok.String()
	return nil
}

// JSONBytes parses a base64 string, in the standard or URL alphabet with or without padding, into *p, or leaves it on null.
func JSONBytes(d *jsontext.Decoder, p *[]byte, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	s := tok.String()
	if tok.Kind() == jsontext.KindString {
		enc := base64.StdEncoding
		if strings.ContainsAny(s, "-_") {
			enc = base64.URLEncoding
		}
		if len(s)%Base64Quantum != 0 {
			enc = enc.WithPadding(base64.NoPadding)
		}
		if *p, err = enc.DecodeString(s); err == nil {
			return nil
		}
	}
	return JSONError(name, ErrInvalidBytes+s)
}

// JSONHex parses a hex string into *p, or leaves it on null.
func JSONHex(d *jsontext.Decoder, p *[]byte, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	s := tok.String()
	if tok.Kind() == jsontext.KindString {
		if *p, err = hex.DecodeString(s); err == nil {
			return nil
		}
	}
	return JSONError(name, ErrInvalidHex+s)
}

// JSONEnum parses a value of enum, given by name in values or by number, into *p; null sets it to zero if nullOK and otherwise leaves it.
func JSONEnum[E ~int32](d *jsontext.Decoder, p *E, values map[string]int32, name, enum string, nullOK bool) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	switch tok.Kind() {
	case jsontext.KindNull:
		if nullOK {
			*p = 0
		}
		return nil
	case jsontext.KindString:
		s := tok.String()
		if n, ok := values[s]; ok {
			*p = E(n)
			return nil
		}
		return JSONError(name, ErrInvalidEnum+enum+": "+strconv.Quote(s))
	}
	v, err := ParseInt(tok, 32, name)
	*p = E(v)
	return err
}

// JSONMsg merges a JSON object into the message at *p, allocating it, or leaves it on null.
func JSONMsg[T any, PT interface {
	*T
	ProtoMergeJSONFrom(*jsontext.Decoder) error
}](d *jsontext.Decoder, p **T, _ string) error {
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return PT(Alloc(p)).ProtoMergeJSONFrom(d)
}

// JSONMsgNull is JSONMsg for google.protobuf.Value, for which null is a value.
func JSONMsgNull[T any, PT interface {
	*T
	ProtoMergeJSONFrom(*jsontext.Decoder) error
}](d *jsontext.Decoder, p **T, _ string) error {
	return PT(Alloc(p)).ProtoMergeJSONFrom(d)
}

// ParseInt parses integer token tok of the given bit width, accepting the exponent and fraction forms of whole numbers.
func ParseInt(tok jsontext.Token, bits int, name string) (int64, error) {
	s, err := JSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	if v, err := strconv.ParseInt(s, 10, bits); err == nil {
		return v, nil
	}
	n := ExactInt(s)
	if n == nil || !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
		return 0, JSONError(name, ErrInvalidInteger+s)
	}
	return n.Int64(), nil
}

// ParseUint parses unsigned integer token tok of the given bit width, accepting the exponent and fraction forms of whole numbers.
func ParseUint(tok jsontext.Token, bits int, name string) (uint64, error) {
	s, err := JSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	if v, err := strconv.ParseUint(s, 10, bits); err == nil {
		return v, nil
	}
	n := ExactInt(s)
	if n == nil || !n.IsUint64() || (bits == 32 && n.Uint64() > math.MaxUint32) {
		return 0, JSONError(name, ErrInvalidInteger+s)
	}
	return n.Uint64(), nil
}

// ExactInt returns the value of JSON number s, or nil if it is not a whole number.
func ExactInt(s string) *big.Int {
	if i := strings.IndexAny(s, "eE"); i >= 0 {
		if e, err := strconv.Atoi(s[i+1:]); err != nil || e > MaxJSONExponent || e < -MaxJSONExponent {
			return nil
		}
	}
	r, ok := new(big.Rat).SetString(s)
	if !ok || !r.IsInt() {
		return nil
	}
	return r.Num()
}

// ParseFloat parses number token tok of the given bit width, or the strings NaN, Infinity and -Infinity.
func ParseFloat(tok jsontext.Token, bits int, name string) (float64, error) {
	if tok.Kind() == jsontext.KindString {
		switch tok.String() {
		case "NaN":
			return math.NaN(), nil
		case "Infinity":
			return math.Inf(1), nil
		case "-Infinity":
			return math.Inf(-1), nil
		}
	}
	s, err := JSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	v, err := strconv.ParseFloat(s, bits)
	if err != nil {
		return 0, JSONError(name, ErrInvalidNumber+s)
	}
	return v, nil
}

// JSONNumber returns the text of number token tok, or of a string token holding a number.
func JSONNumber(tok jsontext.Token, name string) (string, error) {
	s := tok.String()
	if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
		return "", JSONError(name, ErrInvalidNumber+s)
	}
	return s, nil
}

// IntKey parses map key s as an integer of K's width.
func IntKey[K ~int32 | ~int64](s, name, field string) (K, error) {
	bits := 64
	if K(1)<<31 < 0 {
		bits = 32
	}
	k, err := strconv.ParseInt(s, 10, bits)
	if err != nil {
		return 0, JSONError(name, ErrInvalidKey+field+": "+strconv.Quote(s))
	}
	return K(k), nil
}

// UintKey parses map key s as an unsigned integer of K's width.
func UintKey[K ~uint32 | ~uint64](s, name, field string) (K, error) {
	bits := 64
	if ^K(0)>>31 == 1 {
		bits = 32
	}
	k, err := strconv.ParseUint(s, 10, bits)
	if err != nil {
		return 0, JSONError(name, ErrInvalidKey+field+": "+strconv.Quote(s))
	}
	return K(k), nil
}

// BoolKey parses map key s as true or false.
func BoolKey(s, name, field string) (bool, error) {
	switch s {
	case "true":
		return true, nil
	case "false":
		return false, nil
	}
	return false, JSONError(name, ErrInvalidKey+field+": "+strconv.Quote(s))
}

// StringKey returns map key s.
func StringKey(s, _, _ string) (string, error) { return s, nil }

// JSONError returns the error "proto: <name>: <msg>".
func JSONError(name, msg string) error { return errors.New("proto: " + name + ": " + msg) }
