// Code generated by "genmerge -o plan_merge.go . Service Check HTTPCheck:c TCPCheck:c ExecCheck:c"; DO NOT EDIT.

package plan

// Merge merges the fields set in other into s.
func (s *Service) Merge(other *Service) {
	if other.Name != "" {
		s.Name = other.Name
	}
	if other.Summary != "" {
		s.Summary = other.Summary
	}
	if other.Description != "" {
		s.Description = other.Description
	}
	if other.Startup != "" {
		s.Startup = other.Startup
	}
	if other.Override != "" {
		s.Override = other.Override
	}
	if other.Command != "" {
		s.Command = other.Command
	}
	s.After = append(s.After, other.After...)
	s.Before = append(s.Before, other.Before...)
	s.Requires = append(s.Requires, other.Requires...)
	for k, v := range other.Environment {
		if s.Environment == nil {
			s.Environment = make(map[string]string)
		}
		s.Environment[k] = v
	}
	if other.UserID != nil {
		v := *other.UserID
		s.UserID = &v
	}
	if other.User != "" {
		s.User = other.User
	}
	if other.GroupID != nil {
		v := *other.GroupID
		s.GroupID = &v
	}
	if other.Group != "" {
		s.Group = other.Group
	}
	if other.OnSuccess != "" {
		s.OnSuccess = other.OnSuccess
	}
	if other.OnFailure != "" {
		s.OnFailure = other.OnFailure
	}
	for k, v := range other.OnCheckFailure {
		if s.OnCheckFailure == nil {
			s.OnCheckFailure = make(map[string]ServiceAction)
		}
		s.OnCheckFailure[k] = v
	}
	if !other.BackoffDelay.IsZero() {
		s.BackoffDelay = other.BackoffDelay
	}
	if !other.BackoffFactor.IsZero() {
		s.BackoffFactor = other.BackoffFactor
	}
	if !other.BackoffLimit.IsZero() {
		s.BackoffLimit = other.BackoffLimit
	}
}

// Merge merges the fields set in other into c.
func (c *Check) Merge(other *Check) {
	if other.Name != "" {
		c.Name = other.Name
	}
	if other.Override != "" {
		c.Override = other.Override
	}
	if other.Level != "" {
		c.Level = other.Level
	}
	if !other.Period.IsZero() {
		c.Period = other.Period
	}
	if !other.Timeout.IsZero() {
		c.Timeout = other.Timeout
	}
	if other.Failures != 0 {
		c.Failures = other.Failures
	}
	if other.HTTP != nil {
		if c.HTTP == nil {
			c.HTTP = &HTTPCheck{}
		}
		c.HTTP.Merge(other.HTTP)
	}
	if other.TCP != nil {
		if c.TCP == nil {
			c.TCP = &TCPCheck{}
		}
		c.TCP.Merge(other.TCP)
	}
	if other.Exec != nil {
		if c.Exec == nil {
			c.Exec = &ExecCheck{}
		}
		c.Exec.Merge(other.Exec)
	}
}

// Merge merges the fields set in other into c.
func (c *HTTPCheck) Merge(other *HTTPCheck) {
	if other.URL != "" {
		c.URL = other.URL
	}
	for k, v := range other.Headers {
		if c.Headers == nil {
			c.Headers = make(map[string]string)
		}
		c.Headers[k] = v
	}
}

// Merge merges the fields set in other into c.
func (c *TCPCheck) Merge(other *TCPCheck) {
	if other.Port != 0 {
		c.Port = other.Port
	}
	if other.Host != "" {
		c.Host = other.Host
	}
}

// Merge merges the fields set in other into c.
func (c *ExecCheck) Merge(other *ExecCheck) {
	if other.Command != "" {
		c.Command = other.Command
	}
	for k, v := range other.Environment {
		if c.Environment == nil {
			c.Environment = make(map[string]string)
		}
		c.Environment[k] = v
	}
	if other.UserID != nil {
		v := *other.UserID
		c.UserID = &v
	}
	if other.User != "" {
		c.User = other.User
	}
	if other.GroupID != nil {
		v := *other.GroupID
		c.GroupID = &v
	}
	if other.Group != "" {
		c.Group = other.Group
	}
	if other.WorkingDir != "" {
		c.WorkingDir = other.WorkingDir
	}
}
