name: Integration Tests

on:
  push:
    branches: [ master, fips ]
  pull_request:
    branches: [ master, fips ]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: tests

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test -count=1 -tags=integration ./tests/
