name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: tests

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test -count=1 -tags=integration ./tests/
