name: Lint
on: [push, pull_request]

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Run staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@v0.7.0
        staticcheck ./...

    - name: Run govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
        govulncheck ./...
