name: Vulnerability scanning

# TODO: Re-enable once trivy-action supply chain compromise is fully resolved.
# See: https://github.com/aquasecurity/trivy/discussions/10425
on: []
#on:
#  push:
#    branches: [master]
#  pull_request:
#    branches: [master]

permissions: {}

jobs:
  scan:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Github Trivy FS Action
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          ignore-unfixed: true
          trivy-config: .github/trivy.yaml
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          # TODO: Remove the whole "env" section when the issue below is resolved.
          # Known issue: aquasecurity/trivy-action#389.
          # Workaround: https://github.com/orgs/community/discussions/139074#discussioncomment-10808081.
