name: Vulnerability scanning

# TODO: Re-enable once trivy-action supply chain compromise is fully resolved.
# See: https://github.com/aquasecurity/trivy/discussions/10425
on: []

permissions: {}

jobs:
  scan:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Github Trivy FS Action
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1  # v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .github/trivy.yaml
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          # TODO: Remove the whole "env" section when the issue below is resolved.
          # Known issue: aquasecurity/trivy-action#389.
          # Workaround: https://github.com/orgs/community/discussions/139074#discussioncomment-10808081.
