name: Pebble snap

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  release:
    types: [published]

permissions: {}

# We don't want this workflow to have multiple runs in parallel because
# what could happen is that a slow-running and older execution will upload
# an older snap to `edge`, after the newer and latest snap has already been released.
concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DEFAULT_TRACK: latest
  DEFAULT_RISK: edge

jobs:
  local-build:
    runs-on: ubuntu-latest
    # PRS usually come from forks, which are not allowed to access repo secrets.
    # So this job builds the snap locally, and not via LP.
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Pebble repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      # Generate the version for the local snap build.
      - run: go generate ./cmd

      - name: Build Snap
        id: build-snap
        uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79  # v1.3.0

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: snapcraft-logs
          path: |
            ~/.cache/snapcraft/log/
            ~/.local/state/snapcraft/log/
            pebble_*.txt

      - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
        uses: actions/upload-artifact@v7
        with:
          name: pebble-snap-amd64
          path: ${{ steps.build-snap.outputs.snap }}

  remote-build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: true
      matrix:
        # TODO: temporarily pause ppc64el, s390x, and riscv64 builds while builders are broken
        # arch: ["amd64", "arm64", "armhf", "ppc64el", "riscv64", "s390x"]
        arch: ["amd64", "arm64", "armhf"]
    steps:
      - name: Checkout Pebble repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set LP credentials for remote build
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          PEBBLE_DEV_MAILING_LIST: ${{ secrets.PEBBLE_DEV_MAILING_LIST }}
        run: |
          lp_creds_path="$HOME/.local/share/snapcraft/"
          mkdir -p $lp_creds_path
          echo "$LP_CREDENTIALS" > ${lp_creds_path}/launchpad-credentials
          git config --global user.email "$PEBBLE_DEV_MAILING_LIST"
          git config --global user.name "pebble-dev"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      # Ensure Snapcraft will ship the generated version files to LP.
      - run: |
          go generate ./cmd
          git add -f ./cmd/VERSION ./cmd/version_generated.go

      - name: Build Snap for ${{ matrix.arch }}
        id: build-snap
        uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79  # v1.3.0
        with:
          snapcraft-args: --verbosity=debug remote-build --build-for=${{ matrix.arch }} --launchpad-accept-public-upload

      - name: Rename the logs file, for colons are not allowed in the artifact name
        if: always()
        run: cat snapcraft-pebble-*.txt > snapcraft-logs.txt || echo "no log files"

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: snapcraft-logs-${{ matrix.arch }}
          path: |
            ~/.cache/snapcraft/log/
            ~/.local/state/snapcraft/log/
            pebble_*.txt
            snapcraft-logs.txt

      - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
        uses: actions/upload-artifact@v7
        if: steps.build-snap.outcome == 'success'
        with:
          name: pebble-snap-${{ matrix.arch }}
          path: ${{ steps.build-snap.outputs.snap }}

  test:
    runs-on: ubuntu-latest
    needs: [local-build, remote-build]
    env:
      # Testing is only enabled on amd64. We can add arm64 once we have such runners.
      TEST_ON: amd64
    if: |
      always() &&
      (needs.local-build.result == 'success' || needs.local-build.result == 'skipped') &&
      (needs.remote-build.result == 'success' || needs.remote-build.result == 'skipped')
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: pebble-snap-amd64

      - id: get-snap
        run: echo "filename=$(echo pebble*${TEST_ON}*.snap)" >> $GITHUB_OUTPUT

      - name: Install and test snap
        env:
          SNAP_FILENAME: ${{ steps.get-snap.outputs.filename }}
        run: |
          set -ex
          sudo snap install --dangerous --classic "$SNAP_FILENAME"

          # Make sure it is installed
          pebble version --client

          # Run smoke test
          pebble enter --create-dirs exec echo Hello | grep Hello

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name != 'pull_request' && needs.test.result == 'success' && always()
    strategy:
      fail-fast: false
      matrix:
        # TODO: temporarily pause ppc64el, s390x, and riscv64 builds while builders are broken
        # arch: ["amd64", "arm64", "armhf", "ppc64el", "riscv64", "s390x"]
        arch: ["amd64", "arm64", "armhf"]
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: pebble-snap-${{ matrix.arch }}

      - id: get-snap
        env:
          ARCH: ${{ matrix.arch }}
        run: echo "filename=$(echo pebble*${ARCH}*.snap)" >> $GITHUB_OUTPUT

      - name: Release snap to ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}
        uses: snapcore/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40  # v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.get-snap.outputs.filename }}
          release: ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}

  promote:
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'release' && needs.release.result == 'success' && always()
    strategy:
      fail-fast: false
      matrix:
        # TODO: temporarily pause ppc64el, s390x, and riscv64 builds while builders are broken
        # arch: ["amd64", "arm64", "armhf", "ppc64el", "riscv64", "s390x"]
        arch: ["amd64", "arm64", "armhf"]
    env:
      TO_TRACK: latest
      TO_RISK: candidate
    steps:
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Get current ${{ matrix.arch }} snap in ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
        id: get-snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          snapcraft status pebble \
            --track ${{ env.DEFAULT_TRACK }} --arch ${{ matrix.arch }} \
            | awk 'NR==1 { pos = index($0, "Revision") }  /edge/ { print 0+substr($0, pos) }' \
            > revision.txt

          echo "Revision $(cat revision.txt)"
          echo "revision=$(cat revision.txt)" >> $GITHUB_OUTPUT

      # It would be easier to use `snapcraft promote`, but there's an error when trying
      # to avoid the prompt with the "--yes" option:
      # > 'latest/edge' is not a valid set value for --from-channel when using --yes.
      - name: Promote snap to ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          REVISION: ${{ steps.get-snap.outputs.revision }}
        run: |
          snapcraft release pebble \
            "${REVISION}" \
            "${TO_TRACK}/${TO_RISK}"

  sbom-secscan:
    needs: [release]
    if: github.event_name == 'release' && needs.release.result == 'success' && always()
    uses: ./.github/workflows/sbom-secscan.yaml
