name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Unit tests
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        go-version-file: 'go.mod'

    - name: Test and build
      run: |
        go test -race ./... -check.vv
        go build ./cmd/pebble

  root-tests:
    runs-on: ubuntu-latest

    name: Root Tests
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: |
        PEBBLE_TEST_USER=runner PEBBLE_TEST_GROUP=runner sudo -E -H "$(which go)" test ./...

  format:
    runs-on: ubuntu-latest

    name: Format check
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        go-version-file: 'go.mod'

    - name: Ensure no formatting changes
      run: |
        go fmt ./...
        git diff --exit-code

    - name: Ensure no use of empty interface (should be any)
      run: |
        ! egrep -R --exclude-dir .git 'interface\{\}'

  docs:
    runs-on: ubuntu-latest

    name: Automated docs check
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: '3.12' 

    - name: Ensure no CLI reference doc changes
      run: |
        make cli-help
        git diff --exit-code
      working-directory: ./docs
