name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Unit tests
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6
      with:
        go-version-file: 'go.mod'

    - name: Test and build
      run: |
        go test -race ./... -check.vv
        go build ./cmd/pebble

  root-tests:
    runs-on: ubuntu-latest

    name: Root Tests
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: |
        PEBBLE_TEST_USER=runner PEBBLE_TEST_GROUP=runner sudo -E -H "$(which go)" test ./...

  format:
    runs-on: ubuntu-latest

    name: Format check
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6
      with:
        go-version-file: 'go.mod'

    - name: Ensure no formatting changes
      run: |
        go fmt ./...
        git diff --exit-code

    - name: Ensure no use of empty interface (should be any)
      run: |
        ! egrep -R --exclude-dir .git 'interface\{\}'

  docs:
    runs-on: ubuntu-latest

    name: Automated docs check
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6
      with:
        python-version: '3.12' 

    - name: Ensure no CLI reference doc changes
      run: |
        make cli-help
        git diff --exit-code
      working-directory: ./docs
