// Code generated by cotorp. DO NOT EDIT.
// source: trace/v1/trace.proto

package v1

import (
	"cmp"
	"encoding/binary"
	"encoding/hex"
	"encoding/json/jsontext"
	"errors"
	"slices"
	"strconv"

	v12 "github.com/canonical/pebble/internals/otlp/common/v1"
	pb "github.com/canonical/pebble/internals/otlp/internal/pb"
	v11 "github.com/canonical/pebble/internals/otlp/resource/v1"
)

const (
	traceE1 = "proto: field opentelemetry.proto.trace.v1.ResourceSpans.schema_url contains invalid UTF-8"
	traceE2 = "proto: field opentelemetry.proto.trace.v1.ScopeSpans.schema_url contains invalid UTF-8"
	traceE3 = "proto: field opentelemetry.proto.trace.v1.Span.trace_state contains invalid UTF-8"
	traceE4 = "proto: field opentelemetry.proto.trace.v1.Span.name contains invalid UTF-8"
	traceE5 = "proto: field opentelemetry.proto.trace.v1.Span.Event.name contains invalid UTF-8"
	traceE6 = "proto: field opentelemetry.proto.trace.v1.Span.Link.trace_state contains invalid UTF-8"
	traceE7 = "proto: field opentelemetry.proto.trace.v1.Status.message contains invalid UTF-8"
)

// SpanKind is the type of span. Can be used to specify additional relationships between spans
// in addition to a parent/child relationship.
type Span_SpanKind int32

const (
	// Unspecified. Do NOT use as default.
	// Implementations MAY assume SpanKind to be INTERNAL when receiving UNSPECIFIED.
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	// Indicates that the span represents an internal operation within an application,
	// as opposed to an operation happening at the boundaries. Default value.
	Span_SPAN_KIND_INTERNAL Span_SpanKind = 1
	// Indicates that the span covers server-side handling of an RPC or other
	// remote network request.
	Span_SPAN_KIND_SERVER Span_SpanKind = 2
	// Indicates that the span describes a request to some remote service.
	Span_SPAN_KIND_CLIENT Span_SpanKind = 3
	// Indicates that the span describes a producer sending a message to a broker.
	// Unlike CLIENT and SERVER, there is often no direct critical path latency relationship
	// between producer and consumer spans. A PRODUCER span ends when the message was accepted
	// by the broker while the logical processing of the message might span a much longer time.
	Span_SPAN_KIND_PRODUCER Span_SpanKind = 4
	// Indicates that the span describes consumer receiving a message from a broker.
	// Like the PRODUCER kind, there is often no direct critical path latency relationship
	// between producer and consumer spans.
	Span_SPAN_KIND_CONSUMER Span_SpanKind = 5
)

// Span_SpanKind_name maps Span_SpanKind numbers to their names, and Span_SpanKind_value the reverse.
var Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "SPAN_KIND_INTERNAL",
	2: "SPAN_KIND_SERVER",
	3: "SPAN_KIND_CLIENT",
	4: "SPAN_KIND_PRODUCER",
	5: "SPAN_KIND_CONSUMER",
}
var Span_SpanKind_value = pb.Invert(Span_SpanKind_name)

// Enum returns a pointer to a copy of x.
func (x Span_SpanKind) Enum() *Span_SpanKind { return &x }

// String returns the name of x, or its number if it has no name.
func (x Span_SpanKind) String() string { return pb.EnumString(Span_SpanKind_name, int32(x)) }

// IsValid reports whether x is a declared value of Span_SpanKind.
func (x Span_SpanKind) IsValid() bool { return x >= 0 && x <= 5 }

// For the semantics of status codes see
// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status
type Status_StatusCode int32

const (
	// The default status.
	Status_STATUS_CODE_UNSET Status_StatusCode = 0
	// The Span has been validated by an Application developer or Operator to
	// have completed successfully.
	Status_STATUS_CODE_OK Status_StatusCode = 1
	// The Span contains an error.
	Status_STATUS_CODE_ERROR Status_StatusCode = 2
)

// Status_StatusCode_name maps Status_StatusCode numbers to their names, and Status_StatusCode_value the reverse.
var Status_StatusCode_name = map[int32]string{
	0: "STATUS_CODE_UNSET",
	1: "STATUS_CODE_OK",
	2: "STATUS_CODE_ERROR",
}
var Status_StatusCode_value = pb.Invert(Status_StatusCode_name)

// Enum returns a pointer to a copy of x.
func (x Status_StatusCode) Enum() *Status_StatusCode { return &x }

// String returns the name of x, or its number if it has no name.
func (x Status_StatusCode) String() string { return pb.EnumString(Status_StatusCode_name, int32(x)) }

// IsValid reports whether x is a declared value of Status_StatusCode.
func (x Status_StatusCode) IsValid() bool { return x >= 0 && x <= 2 }

// SpanFlags represents constants used to interpret the
// Span.flags field, which is protobuf 'fixed32' type and is to
// be used as bit-fields. Each non-zero value defined in this enum is
// a bit-mask.  To extract the bit-field, for example, use an
// expression like:
//
//	(span.flags & SPAN_FLAGS_TRACE_FLAGS_MASK)
//
// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
//
// Note that Span flags were introduced in version 1.1 of the
// OpenTelemetry protocol.  Older Span producers do not set this
// field, consequently consumers should not rely on the absence of a
// particular flag bit to indicate the presence of a particular feature.
type SpanFlags int32

const (
	// The zero value for the enum. Should not be used for comparisons.
	// Instead use bitwise "and" with the appropriate mask as shown above.
	SpanFlags_SPAN_FLAGS_DO_NOT_USE SpanFlags = 0
	// Bits 0-7 are used for trace flags.
	SpanFlags_SPAN_FLAGS_TRACE_FLAGS_MASK SpanFlags = 255
	// Bits 8 and 9 are used to indicate that the parent span or link span is remote.
	// Bit 8 (`HAS_IS_REMOTE`) indicates whether the value is known.
	// Bit 9 (`IS_REMOTE`) indicates whether the span or link is remote.
	SpanFlags_SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK SpanFlags = 256
	SpanFlags_SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK     SpanFlags = 512
)

// SpanFlags_name maps SpanFlags numbers to their names, and SpanFlags_value the reverse.
var SpanFlags_name = map[int32]string{
	0:   "SPAN_FLAGS_DO_NOT_USE",
	255: "SPAN_FLAGS_TRACE_FLAGS_MASK",
	256: "SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK",
	512: "SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK",
}
var SpanFlags_value = pb.Invert(SpanFlags_name)

// Enum returns a pointer to a copy of x.
func (x SpanFlags) Enum() *SpanFlags { return &x }

// String returns the name of x, or its number if it has no name.
func (x SpanFlags) String() string { return pb.EnumString(SpanFlags_name, int32(x)) }

// IsValid reports whether x is a declared value of SpanFlags.
func (x SpanFlags) IsValid() bool { return x == 0 || (x >= 255 && x <= 256) || x == 512 }

// TracesData represents the traces data that can be stored in a persistent storage,
// OR can be embedded by other protocols that transfer OTLP traces data but do
// not implement the OTLP protocol.
//
// The main difference between this message and collector protocol is that
// in this message there will not be any "control" or "metadata" specific to
// OTLP protocol.
//
// When new fields are added into this message, the OTLP request MUST be updated
// as well.
type TracesData struct {
	// An array of ResourceSpans.
	// For data coming from a single resource this array will typically contain
	// one element. Intermediary nodes that receive data from multiple origins
	// typically batch the data before forwarding further and in that case this
	// array will contain multiple elements.
	ResourceSpans []*ResourceSpans

	u []byte
}

// Reset clears all fields of m.
func (m *TracesData) Reset()                             { *m = TracesData{} }
func (m *TracesData) z() *TracesData                     { return pb.If(m == nil, &traceZTracesData, m) }
func (m *TracesData) GetResourceSpans() []*ResourceSpans { return m.z().ResourceSpans }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *TracesData) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *TracesData) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsgs(1, m.ResourceSpans, func(v *ResourceSpans) int { return v.ProtoSize() })
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *TracesData) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *TracesData) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *TracesData) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	for _, v := range slices.Backward(m.ResourceSpans) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *TracesData) UnmarshalBinary(b []byte) error {
	*m = TracesData{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *TracesData) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *TracesData) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.ResourceSpans)).ProtoMergeDepth(x, depth+1)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *TracesData) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *TracesData) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *TracesData) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *TracesData) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendList(b, ",\"resourceSpans\":[", m.ResourceSpans, (*ResourceSpans).ProtoAppendJSON, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *TracesData) UnmarshalJSON(b []byte) error { *m = TracesData{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *TracesData) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.TracesData", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *TracesData) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = TracesData{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *TracesData) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [1]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.TracesData"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "resourceSpans", "resource_spans":
			err = pb.RepField(d, &seen[0], key, "opentelemetry.proto.trace.v1.TracesData", &m.ResourceSpans, false, pb.JSONMsg)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// A collection of ScopeSpans from a Resource.
type ResourceSpans struct {
	// The resource for the spans in this message.
	// If this field is not set then no resource info is known.
	Resource *v11.Resource
	// A list of ScopeSpans that originate from a resource.
	ScopeSpans []*ScopeSpans
	// The Schema URL, if known. This is the identifier of the Schema that the resource data
	// is recorded in. Notably, the last part of the URL path is the version number of the
	// schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to the data in the "resource" field. It does not apply
	// to the data in the "scope_spans" field which have their own schema_url field.
	SchemaUrl string

	u []byte
}

// Reset clears all fields of m.
func (m *ResourceSpans) Reset()                       { *m = ResourceSpans{} }
func (m *ResourceSpans) z() *ResourceSpans            { return pb.If(m == nil, &traceZResourceSpans, m) }
func (m *ResourceSpans) GetResource() *v11.Resource   { return m.z().Resource }
func (m *ResourceSpans) GetScopeSpans() []*ScopeSpans { return m.z().ScopeSpans }
func (m *ResourceSpans) GetSchemaUrl() string         { return m.z().SchemaUrl }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *ResourceSpans) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ResourceSpans) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsg(1, m.Resource, func(v *v11.Resource) int { return v.ProtoSize() })
	n += pb.SizeMsgs(1, m.ScopeSpans, func(v *ScopeSpans) int { return v.ProtoSize() })
	n += pb.SizeLenField(1, len(m.SchemaUrl))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ResourceSpans) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *ResourceSpans) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *ResourceSpans) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.SchemaUrl, traceE1, nil); err != nil {
		return 0, err
	}
	i = pb.PutStringField(b, i, m.SchemaUrl, 3<<pb.TagTypeBits|pb.WireBytes)
	for _, v := range slices.Backward(m.ScopeSpans) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 2<<pb.TagTypeBits|pb.WireBytes)
	}
	if m.Resource != nil {
		n, err := m.Resource.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *ResourceSpans) UnmarshalBinary(b []byte) error {
	*m = ResourceSpans{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *ResourceSpans) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ResourceSpans) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(&m.Resource).ProtoMergeDepth(x, depth+1)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.ScopeSpans)).ProtoMergeDepth(x, depth+1)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.SchemaUrl, traceE1)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *ResourceSpans) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ResourceSpans) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *ResourceSpans) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *ResourceSpans) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendMsg(b, ",\"resource\":", m.Resource, func(v *v11.Resource, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	b, err = pb.AppendList(b, ",\"scopeSpans\":[", m.ScopeSpans, (*ScopeSpans).ProtoAppendJSON, err)
	if len(m.SchemaUrl) > 0 {
		b, err = pb.Quote(append(b, ",\"schemaUrl\":"...), m.SchemaUrl, err)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *ResourceSpans) UnmarshalJSON(b []byte) error {
	*m = ResourceSpans{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *ResourceSpans) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.ResourceSpans", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *ResourceSpans) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = ResourceSpans{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *ResourceSpans) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [3]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.ResourceSpans"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "resource":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.ResourceSpans", &m.Resource, pb.JSONMsg)
		case "scopeSpans", "scope_spans":
			err = pb.RepField(d, &seen[1], key, "opentelemetry.proto.trace.v1.ResourceSpans", &m.ScopeSpans, false, pb.JSONMsg)
		case "schemaUrl", "schema_url":
			err = pb.Field(d, &seen[2], key, "opentelemetry.proto.trace.v1.ResourceSpans", &m.SchemaUrl, pb.JSONString)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// A collection of Spans produced by an InstrumentationScope.
type ScopeSpans struct {
	// The instrumentation scope information for the spans in this message.
	// Semantically when InstrumentationScope isn't set, it is equivalent with
	// an empty instrumentation scope name (unknown).
	Scope *v12.InstrumentationScope
	// A list of Spans that originate from an instrumentation scope.
	Spans []*Span
	// The Schema URL, if known. This is the identifier of the Schema that the span data
	// is recorded in. Notably, the last part of the URL path is the version number of the
	// schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to the data in the "scope" field and all spans and span
	// events in the "spans" field.
	SchemaUrl string

	u []byte
}

// Reset clears all fields of m.
func (m *ScopeSpans) Reset()                              { *m = ScopeSpans{} }
func (m *ScopeSpans) z() *ScopeSpans                      { return pb.If(m == nil, &traceZScopeSpans, m) }
func (m *ScopeSpans) GetScope() *v12.InstrumentationScope { return m.z().Scope }
func (m *ScopeSpans) GetSpans() []*Span                   { return m.z().Spans }
func (m *ScopeSpans) GetSchemaUrl() string                { return m.z().SchemaUrl }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *ScopeSpans) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ScopeSpans) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeMsg(1, m.Scope, func(v *v12.InstrumentationScope) int { return v.ProtoSize() })
	n += pb.SizeMsgs(1, m.Spans, func(v *Span) int { return v.ProtoSize() })
	n += pb.SizeLenField(1, len(m.SchemaUrl))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ScopeSpans) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *ScopeSpans) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *ScopeSpans) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.SchemaUrl, traceE2, nil); err != nil {
		return 0, err
	}
	i = pb.PutStringField(b, i, m.SchemaUrl, 3<<pb.TagTypeBits|pb.WireBytes)
	for _, v := range slices.Backward(m.Spans) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 2<<pb.TagTypeBits|pb.WireBytes)
	}
	if m.Scope != nil {
		n, err := m.Scope.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 1<<pb.TagTypeBits|pb.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *ScopeSpans) UnmarshalBinary(b []byte) error {
	*m = ScopeSpans{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *ScopeSpans) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ScopeSpans) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(&m.Scope).ProtoMergeDepth(x, depth+1)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Spans)).ProtoMergeDepth(x, depth+1)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.SchemaUrl, traceE2)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *ScopeSpans) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ScopeSpans) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *ScopeSpans) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *ScopeSpans) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	b, err = pb.AppendMsg(b, ",\"scope\":", m.Scope, func(v *v12.InstrumentationScope, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	b, err = pb.AppendList(b, ",\"spans\":[", m.Spans, (*Span).ProtoAppendJSON, err)
	if len(m.SchemaUrl) > 0 {
		b, err = pb.Quote(append(b, ",\"schemaUrl\":"...), m.SchemaUrl, err)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *ScopeSpans) UnmarshalJSON(b []byte) error { *m = ScopeSpans{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *ScopeSpans) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.ScopeSpans", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *ScopeSpans) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = ScopeSpans{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *ScopeSpans) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [3]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.ScopeSpans"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "scope":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.ScopeSpans", &m.Scope, pb.JSONMsg)
		case "spans":
			err = pb.RepField(d, &seen[1], key, "opentelemetry.proto.trace.v1.ScopeSpans", &m.Spans, false, pb.JSONMsg)
		case "schemaUrl", "schema_url":
			err = pb.Field(d, &seen[2], key, "opentelemetry.proto.trace.v1.ScopeSpans", &m.SchemaUrl, pb.JSONString)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// A Span represents a single operation performed by a single component of the system.
//
// The next available field id is 17.
type Span struct {
	// A unique identifier for a trace. All spans from the same trace share
	// the same `trace_id`. The ID is a 16-byte array. An ID with all zeroes OR
	// of length other than 16 bytes is considered invalid (empty string in OTLP/JSON
	// is zero-length and thus is also invalid).
	//
	// This field is required.
	TraceId []byte
	// A unique identifier for a span within a trace, assigned when the span
	// is created. The ID is an 8-byte array. An ID with all zeroes OR of length
	// other than 8 bytes is considered invalid (empty string in OTLP/JSON
	// is zero-length and thus is also invalid).
	//
	// This field is required.
	SpanId []byte
	// trace_state conveys information about request position in multiple distributed tracing graphs.
	// It is a trace_state in w3c-trace-context format: https://www.w3.org/TR/trace-context/#tracestate-header
	// See also https://github.com/w3c/distributed-tracing for more details about this field.
	TraceState string
	// The `span_id` of this span's parent span. If this is a root span, then this
	// field must be empty. The ID is an 8-byte array.
	ParentSpanId []byte
	// Flags, a bit field.
	//
	// Bits 0-7 (8 least significant bits) are the trace flags as defined in W3C Trace
	// Context specification. To read the 8-bit W3C trace flag, use
	// `flags & SPAN_FLAGS_TRACE_FLAGS_MASK`.
	//
	// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
	//
	// Bits 8 and 9 represent the 3 states of whether a span's parent
	// is remote. The states are (unknown, is not remote, is remote).
	// To read whether the value is known, use `(flags & SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK) != 0`.
	// To read whether the span is remote, use `(flags & SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK) != 0`.
	//
	// When creating span messages, if the message is logically forwarded from another source
	// with an equivalent flags fields (i.e., usually another OTLP span message), the field SHOULD
	// be copied as-is. If creating from a source that does not have an equivalent flags field
	// (such as a runtime representation of an OpenTelemetry span), the high 22 bits MUST
	// be set to zero.
	// Readers MUST NOT assume that bits 10-31 (22 most significant bits) will be zero.
	//
	// [Optional].
	Flags uint32
	// A description of the span's operation.
	//
	// For example, the name can be a qualified method name or a file name
	// and a line number where the operation is called. A best practice is to use
	// the same display name at the same call point in an application.
	// This makes it easier to correlate spans in different traces.
	//
	// This field is semantically required to be set to non-empty string.
	// Empty value is equivalent to an unknown span name.
	//
	// This field is required.
	Name string
	// Distinguishes between spans generated in a particular context. For example,
	// two spans with the same name may be distinguished using `CLIENT` (caller)
	// and `SERVER` (callee) to identify queueing latency associated with the span.
	Kind Span_SpanKind
	// The start time of the span. On the client side, this is the time
	// kept by the local machine where the span execution starts. On the server side, this
	// is the time when the server's application handler starts running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	StartTimeUnixNano uint64
	// The end time of the span. On the client side, this is the time
	// kept by the local machine where the span execution ends. On the server side, this
	// is the time when the server application handler stops running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	EndTimeUnixNano uint64
	// A collection of key/value pairs. Note, global attributes
	// like server name can be set using the resource API. Examples of attributes:
	//
	//     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
	//     "/http/server_latency": 300
	//     "example.com/myattribute": true
	//     "example.com/score": 10.239
	//
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*v12.KeyValue
	// The number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32
	// A collection of Event items.
	Events []*Span_Event
	// The number of dropped events. If the value is 0, then no
	// events were dropped.
	DroppedEventsCount uint32
	// A collection of Links, which are references from this span to a span
	// in the same or different trace.
	Links []*Span_Link
	// The number of dropped links after the maximum size was
	// enforced. If this value is 0, then no links were dropped.
	DroppedLinksCount uint32
	// An optional final status for this span. Semantically when Status isn't set, it means
	// span's status code is unset, i.e. assume STATUS_CODE_UNSET (code = 0).
	Status *Status

	u []byte
}

// Reset clears all fields of m.
func (m *Span) Reset()                            { *m = Span{} }
func (m *Span) z() *Span                          { return pb.If(m == nil, &traceZSpan, m) }
func (m *Span) GetTraceId() []byte                { return m.z().TraceId }
func (m *Span) GetSpanId() []byte                 { return m.z().SpanId }
func (m *Span) GetTraceState() string             { return m.z().TraceState }
func (m *Span) GetParentSpanId() []byte           { return m.z().ParentSpanId }
func (m *Span) GetFlags() uint32                  { return m.z().Flags }
func (m *Span) GetName() string                   { return m.z().Name }
func (m *Span) GetKind() Span_SpanKind            { return m.z().Kind }
func (m *Span) GetStartTimeUnixNano() uint64      { return m.z().StartTimeUnixNano }
func (m *Span) GetEndTimeUnixNano() uint64        { return m.z().EndTimeUnixNano }
func (m *Span) GetAttributes() []*v12.KeyValue    { return m.z().Attributes }
func (m *Span) GetDroppedAttributesCount() uint32 { return m.z().DroppedAttributesCount }
func (m *Span) GetEvents() []*Span_Event          { return m.z().Events }
func (m *Span) GetDroppedEventsCount() uint32     { return m.z().DroppedEventsCount }
func (m *Span) GetLinks() []*Span_Link            { return m.z().Links }
func (m *Span) GetDroppedLinksCount() uint32      { return m.z().DroppedLinksCount }
func (m *Span) GetStatus() *Status                { return m.z().Status }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Span) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.TraceId))
	n += pb.SizeLenField(1, len(m.SpanId))
	n += pb.SizeLenField(1, len(m.TraceState))
	n += pb.SizeLenField(1, len(m.ParentSpanId))
	n += pb.SizeLenField(1, len(m.Name))
	n += pb.SizeVarint(1, uint64(int64(m.Kind)))
	n += pb.SizeFixed(1, pb.Fixed64Size, m.StartTimeUnixNano != 0)
	n += pb.SizeFixed(1, pb.Fixed64Size, m.EndTimeUnixNano != 0)
	n += pb.SizeMsgs(1, m.Attributes, func(v *v12.KeyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedAttributesCount))
	n += pb.SizeMsgs(1, m.Events, func(v *Span_Event) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedEventsCount))
	n += pb.SizeMsgs(1, m.Links, func(v *Span_Link) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedLinksCount))
	n += pb.SizeMsg(1, m.Status, func(v *Status) int { return v.ProtoSize() })
	n += pb.SizeFixed(2, pb.Fixed32Size, m.Flags != 0)
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Span) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Name, traceE4, pb.CheckUTF8(m.TraceState, traceE3, nil)); err != nil {
		return 0, err
	}
	i = pb.PutFixed32Field2(b, i, uint32(m.Flags), 16<<pb.TagTypeBits|pb.WireFixed32)
	if m.Status != nil {
		n, err := m.Status.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 15<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedLinksCount), 14<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Links) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 13<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedEventsCount), 12<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Events) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 11<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedAttributesCount), 10<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 9<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutFixed64Field(b, i, uint64(m.EndTimeUnixNano), 8<<pb.TagTypeBits|pb.WireFixed64)
	i = pb.PutFixed64Field(b, i, uint64(m.StartTimeUnixNano), 7<<pb.TagTypeBits|pb.WireFixed64)
	i = pb.PutVarintField(b, i, uint64(int64(m.Kind)), 6<<pb.TagTypeBits|pb.WireVarint)
	i = pb.PutStringField(b, i, m.Name, 5<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutBytesField(b, i, m.ParentSpanId, 4<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutStringField(b, i, m.TraceState, 3<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutBytesField(b, i, m.SpanId, 2<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutBytesField(b, i, m.TraceId, 1<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Span) UnmarshalBinary(b []byte) error { *m = Span{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Span) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			n = pb.Bytes(b, &m.TraceId)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n = pb.Bytes(b, &m.SpanId)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.TraceState, traceE3)
		case 4<<pb.TagTypeBits | pb.WireBytes:
			n = pb.Bytes(b, &m.ParentSpanId)
		case 5<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Name, traceE4)
		case 6<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.Kind)
		case 7<<pb.TagTypeBits | pb.WireFixed64:
			n = pb.Fixed64(b, &m.StartTimeUnixNano)
		case 8<<pb.TagTypeBits | pb.WireFixed64:
			n = pb.Fixed64(b, &m.EndTimeUnixNano)
		case 9<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Attributes)).ProtoMergeDepth(x, depth+1)
		case 10<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedAttributesCount)
		case 11<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Events)).ProtoMergeDepth(x, depth+1)
		case 12<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedEventsCount)
		case 13<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Links)).ProtoMergeDepth(x, depth+1)
		case 14<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedLinksCount)
		case 15<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(&m.Status).ProtoMergeDepth(x, depth+1)
		case 16<<pb.TagTypeBits | pb.WireFixed32:
			n = pb.Fixed32(b, &m.Flags)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Span) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Span) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Span) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.TraceId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"traceId\":\""...), m.TraceId), '"')
	}
	if len(m.SpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"spanId\":\""...), m.SpanId), '"')
	}
	if len(m.TraceState) > 0 {
		b, err = pb.Quote(append(b, ",\"traceState\":"...), m.TraceState, err)
	}
	if len(m.ParentSpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"parentSpanId\":\""...), m.ParentSpanId), '"')
	}
	if m.Flags != 0 {
		b = strconv.AppendUint(append(b, ",\"flags\":"...), uint64(m.Flags), 10)
	}
	if len(m.Name) > 0 {
		b, err = pb.Quote(append(b, ",\"name\":"...), m.Name, err)
	}
	if m.Kind != 0 {
		b = strconv.AppendInt(append(b, ",\"kind\":"...), int64(m.Kind), 10)
	}
	if m.StartTimeUnixNano != 0 {
		b = append(strconv.AppendUint(append(b, ",\"startTimeUnixNano\":\""...), m.StartTimeUnixNano, 10), '"')
	}
	if m.EndTimeUnixNano != 0 {
		b = append(strconv.AppendUint(append(b, ",\"endTimeUnixNano\":\""...), m.EndTimeUnixNano, 10), '"')
	}
	b, err = pb.AppendList(b, ",\"attributes\":[", m.Attributes, (*v12.KeyValue).ProtoAppendJSON, err)
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	b, err = pb.AppendList(b, ",\"events\":[", m.Events, (*Span_Event).ProtoAppendJSON, err)
	if m.DroppedEventsCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedEventsCount\":"...), uint64(m.DroppedEventsCount), 10)
	}
	b, err = pb.AppendList(b, ",\"links\":[", m.Links, (*Span_Link).ProtoAppendJSON, err)
	if m.DroppedLinksCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedLinksCount\":"...), uint64(m.DroppedLinksCount), 10)
	}
	b, err = pb.AppendMsg(b, ",\"status\":", m.Status, func(v *Status, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Span) UnmarshalJSON(b []byte) error { *m = Span{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Span) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.Span", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Span) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Span{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Span) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [16]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.Span"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "traceId", "trace_id":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.Span", &m.TraceId, pb.JSONHex)
		case "spanId", "span_id":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.trace.v1.Span", &m.SpanId, pb.JSONHex)
		case "traceState", "trace_state":
			err = pb.Field(d, &seen[2], key, "opentelemetry.proto.trace.v1.Span", &m.TraceState, pb.JSONString)
		case "parentSpanId", "parent_span_id":
			err = pb.Field(d, &seen[3], key, "opentelemetry.proto.trace.v1.Span", &m.ParentSpanId, pb.JSONHex)
		case "flags":
			err = pb.Field(d, &seen[4], key, "opentelemetry.proto.trace.v1.Span", &m.Flags, pb.JSONUint)
		case "name":
			err = pb.Field(d, &seen[5], key, "opentelemetry.proto.trace.v1.Span", &m.Name, pb.JSONString)
		case "kind":
			err = pb.Field(d, &seen[6], key, "opentelemetry.proto.trace.v1.Span", &m.Kind, traceJSpanSpanKind)
		case "startTimeUnixNano", "start_time_unix_nano":
			err = pb.Field(d, &seen[7], key, "opentelemetry.proto.trace.v1.Span", &m.StartTimeUnixNano, pb.JSONUint)
		case "endTimeUnixNano", "end_time_unix_nano":
			err = pb.Field(d, &seen[8], key, "opentelemetry.proto.trace.v1.Span", &m.EndTimeUnixNano, pb.JSONUint)
		case "attributes":
			err = pb.RepField(d, &seen[9], key, "opentelemetry.proto.trace.v1.Span", &m.Attributes, false, pb.JSONMsg)
		case "droppedAttributesCount", "dropped_attributes_count":
			err = pb.Field(d, &seen[10], key, "opentelemetry.proto.trace.v1.Span", &m.DroppedAttributesCount, pb.JSONUint)
		case "events":
			err = pb.RepField(d, &seen[11], key, "opentelemetry.proto.trace.v1.Span", &m.Events, false, pb.JSONMsg)
		case "droppedEventsCount", "dropped_events_count":
			err = pb.Field(d, &seen[12], key, "opentelemetry.proto.trace.v1.Span", &m.DroppedEventsCount, pb.JSONUint)
		case "links":
			err = pb.RepField(d, &seen[13], key, "opentelemetry.proto.trace.v1.Span", &m.Links, false, pb.JSONMsg)
		case "droppedLinksCount", "dropped_links_count":
			err = pb.Field(d, &seen[14], key, "opentelemetry.proto.trace.v1.Span", &m.DroppedLinksCount, pb.JSONUint)
		case "status":
			err = pb.Field(d, &seen[15], key, "opentelemetry.proto.trace.v1.Span", &m.Status, pb.JSONMsg)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

func traceJSpanSpanKind(d *jsontext.Decoder, p *Span_SpanKind, name string) error {
	return pb.JSONEnum(d, p, Span_SpanKind_value, name, "opentelemetry.proto.trace.v1.Span.SpanKind", false)
}

// Event is a time-stamped annotation of the span, consisting of user-supplied
// text description and key-value pairs.
type Span_Event struct {
	// The time the event occurred.
	TimeUnixNano uint64
	// The name of the event.
	// This field is semantically required to be set to non-empty string.
	Name string
	// A collection of attribute key/value pairs on the event.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*v12.KeyValue
	// The number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32

	u []byte
}

// Reset clears all fields of m.
func (m *Span_Event) Reset()                            { *m = Span_Event{} }
func (m *Span_Event) z() *Span_Event                    { return pb.If(m == nil, &traceZSpan_Event, m) }
func (m *Span_Event) GetTimeUnixNano() uint64           { return m.z().TimeUnixNano }
func (m *Span_Event) GetName() string                   { return m.z().Name }
func (m *Span_Event) GetAttributes() []*v12.KeyValue    { return m.z().Attributes }
func (m *Span_Event) GetDroppedAttributesCount() uint32 { return m.z().DroppedAttributesCount }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Span_Event) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span_Event) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeFixed(1, pb.Fixed64Size, m.TimeUnixNano != 0)
	n += pb.SizeLenField(1, len(m.Name))
	n += pb.SizeMsgs(1, m.Attributes, func(v *v12.KeyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedAttributesCount))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span_Event) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span_Event) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Span_Event) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Name, traceE5, nil); err != nil {
		return 0, err
	}
	i = pb.PutVarintField(b, i, uint64(m.DroppedAttributesCount), 4<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 3<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutStringField(b, i, m.Name, 2<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutFixed64Field(b, i, uint64(m.TimeUnixNano), 1<<pb.TagTypeBits|pb.WireFixed64)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Span_Event) UnmarshalBinary(b []byte) error {
	*m = Span_Event{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Span_Event) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span_Event) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireFixed64:
			n = pb.Fixed64(b, &m.TimeUnixNano)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Name, traceE5)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Attributes)).ProtoMergeDepth(x, depth+1)
		case 4<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedAttributesCount)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Span_Event) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span_Event) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Span_Event) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Span_Event) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if m.TimeUnixNano != 0 {
		b = append(strconv.AppendUint(append(b, ",\"timeUnixNano\":\""...), m.TimeUnixNano, 10), '"')
	}
	if len(m.Name) > 0 {
		b, err = pb.Quote(append(b, ",\"name\":"...), m.Name, err)
	}
	b, err = pb.AppendList(b, ",\"attributes\":[", m.Attributes, (*v12.KeyValue).ProtoAppendJSON, err)
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Span_Event) UnmarshalJSON(b []byte) error { *m = Span_Event{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Span_Event) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.Span.Event", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Span_Event) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Span_Event{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Span_Event) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [4]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.Span.Event"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "timeUnixNano", "time_unix_nano":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.Span.Event", &m.TimeUnixNano, pb.JSONUint)
		case "name":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.trace.v1.Span.Event", &m.Name, pb.JSONString)
		case "attributes":
			err = pb.RepField(d, &seen[2], key, "opentelemetry.proto.trace.v1.Span.Event", &m.Attributes, false, pb.JSONMsg)
		case "droppedAttributesCount", "dropped_attributes_count":
			err = pb.Field(d, &seen[3], key, "opentelemetry.proto.trace.v1.Span.Event", &m.DroppedAttributesCount, pb.JSONUint)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// A pointer from the current span to another span in the same trace or in a
// different trace. For example, this can be used in batching operations,
// where a single batch handler processes multiple requests from different
// traces or when the handler receives a request from a different project.
type Span_Link struct {
	// A unique identifier of a trace that this linked span is part of. The ID is a
	// 16-byte array.
	TraceId []byte
	// A unique identifier for the linked span. The ID is an 8-byte array.
	SpanId []byte
	// The trace_state associated with the link.
	TraceState string
	// A collection of attribute key/value pairs on the link.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	// The behavior of software that receives duplicated keys can be unpredictable.
	Attributes []*v12.KeyValue
	// The number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32
	// Flags, a bit field.
	//
	// Bits 0-7 (8 least significant bits) are the trace flags as defined in W3C Trace
	// Context specification. To read the 8-bit W3C trace flag, use
	// `flags & SPAN_FLAGS_TRACE_FLAGS_MASK`.
	//
	// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
	//
	// Bits 8 and 9 represent the 3 states of whether the link is remote.
	// The states are (unknown, is not remote, is remote).
	// To read whether the value is known, use `(flags & SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK) != 0`.
	// To read whether the link is remote, use `(flags & SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK) != 0`.
	//
	// Readers MUST NOT assume that bits 10-31 (22 most significant bits) will be zero.
	// When creating new spans, bits 10-31 (most-significant 22-bits) MUST be zero.
	//
	// [Optional].
	Flags uint32

	u []byte
}

// Reset clears all fields of m.
func (m *Span_Link) Reset()                            { *m = Span_Link{} }
func (m *Span_Link) z() *Span_Link                     { return pb.If(m == nil, &traceZSpan_Link, m) }
func (m *Span_Link) GetTraceId() []byte                { return m.z().TraceId }
func (m *Span_Link) GetSpanId() []byte                 { return m.z().SpanId }
func (m *Span_Link) GetTraceState() string             { return m.z().TraceState }
func (m *Span_Link) GetAttributes() []*v12.KeyValue    { return m.z().Attributes }
func (m *Span_Link) GetDroppedAttributesCount() uint32 { return m.z().DroppedAttributesCount }
func (m *Span_Link) GetFlags() uint32                  { return m.z().Flags }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Span_Link) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span_Link) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.TraceId))
	n += pb.SizeLenField(1, len(m.SpanId))
	n += pb.SizeLenField(1, len(m.TraceState))
	n += pb.SizeMsgs(1, m.Attributes, func(v *v12.KeyValue) int { return v.ProtoSize() })
	n += pb.SizeVarint(1, uint64(m.DroppedAttributesCount))
	n += pb.SizeFixed(1, pb.Fixed32Size, m.Flags != 0)
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span_Link) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span_Link) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Span_Link) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.TraceState, traceE6, nil); err != nil {
		return 0, err
	}
	i = pb.PutFixed32Field(b, i, uint32(m.Flags), 6<<pb.TagTypeBits|pb.WireFixed32)
	i = pb.PutVarintField(b, i, uint64(m.DroppedAttributesCount), 5<<pb.TagTypeBits|pb.WireVarint)
	for _, v := range slices.Backward(m.Attributes) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = pb.PutVarint(b, pb.PutVarint(b, i-n, uint64(n)), 4<<pb.TagTypeBits|pb.WireBytes)
	}
	i = pb.PutStringField(b, i, m.TraceState, 3<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutBytesField(b, i, m.SpanId, 2<<pb.TagTypeBits|pb.WireBytes)
	i = pb.PutBytesField(b, i, m.TraceId, 1<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Span_Link) UnmarshalBinary(b []byte) error { *m = Span_Link{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Span_Link) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span_Link) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<pb.TagTypeBits | pb.WireBytes:
			n = pb.Bytes(b, &m.TraceId)
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n = pb.Bytes(b, &m.SpanId)
		case 3<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.TraceState, traceE6)
		case 4<<pb.TagTypeBits | pb.WireBytes:
			x, n = pb.ReadBytes(b)
			err = pb.Alloc(pb.Grow(&m.Attributes)).ProtoMergeDepth(x, depth+1)
		case 5<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.DroppedAttributesCount)
		case 6<<pb.TagTypeBits | pb.WireFixed32:
			n = pb.Fixed32(b, &m.Flags)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Span_Link) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span_Link) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Span_Link) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Span_Link) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.TraceId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"traceId\":\""...), m.TraceId), '"')
	}
	if len(m.SpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"spanId\":\""...), m.SpanId), '"')
	}
	if len(m.TraceState) > 0 {
		b, err = pb.Quote(append(b, ",\"traceState\":"...), m.TraceState, err)
	}
	b, err = pb.AppendList(b, ",\"attributes\":[", m.Attributes, (*v12.KeyValue).ProtoAppendJSON, err)
	if m.DroppedAttributesCount != 0 {
		b = strconv.AppendUint(append(b, ",\"droppedAttributesCount\":"...), uint64(m.DroppedAttributesCount), 10)
	}
	if m.Flags != 0 {
		b = strconv.AppendUint(append(b, ",\"flags\":"...), uint64(m.Flags), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Span_Link) UnmarshalJSON(b []byte) error { *m = Span_Link{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Span_Link) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.Span.Link", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Span_Link) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Span_Link{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Span_Link) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [6]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.Span.Link"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "traceId", "trace_id":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.Span.Link", &m.TraceId, pb.JSONHex)
		case "spanId", "span_id":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.trace.v1.Span.Link", &m.SpanId, pb.JSONHex)
		case "traceState", "trace_state":
			err = pb.Field(d, &seen[2], key, "opentelemetry.proto.trace.v1.Span.Link", &m.TraceState, pb.JSONString)
		case "attributes":
			err = pb.RepField(d, &seen[3], key, "opentelemetry.proto.trace.v1.Span.Link", &m.Attributes, false, pb.JSONMsg)
		case "droppedAttributesCount", "dropped_attributes_count":
			err = pb.Field(d, &seen[4], key, "opentelemetry.proto.trace.v1.Span.Link", &m.DroppedAttributesCount, pb.JSONUint)
		case "flags":
			err = pb.Field(d, &seen[5], key, "opentelemetry.proto.trace.v1.Span.Link", &m.Flags, pb.JSONUint)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

// The Status type defines a logical error model that is suitable for different
// programming environments, including REST APIs and RPC APIs.
type Status struct {
	// A developer-facing human readable error message.
	Message string
	// The status code.
	Code Status_StatusCode

	u []byte
}

// Reset clears all fields of m.
func (m *Status) Reset()                     { *m = Status{} }
func (m *Status) z() *Status                 { return pb.If(m == nil, &traceZStatus, m) }
func (m *Status) GetMessage() string         { return m.z().Message }
func (m *Status) GetCode() Status_StatusCode { return m.z().Code }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Status) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Status) ProtoSize() (n int) {
	m = m.z()
	n += pb.SizeLenField(1, len(m.Message))
	n += pb.SizeVarint(1, uint64(int64(m.Code)))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Status) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Status) AppendBinary(b []byte) ([]byte, error) {
	return pb.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Status) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := pb.CopyUnknown(b, len(b), m.u)
	if err := pb.CheckUTF8(m.Message, traceE7, nil); err != nil {
		return 0, err
	}
	i = pb.PutVarintField(b, i, uint64(int64(m.Code)), 3<<pb.TagTypeBits|pb.WireVarint)
	i = pb.PutStringField(b, i, m.Message, 2<<pb.TagTypeBits|pb.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Status) UnmarshalBinary(b []byte) error { *m = Status{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Status) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Status) ProtoMergeDepth(b []byte, depth int) error {
	err := pb.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 2<<pb.TagTypeBits | pb.WireBytes:
			n, err = pb.String(b, &m.Message, traceE7)
		case 3<<pb.TagTypeBits | pb.WireVarint:
			n = pb.Varint(b, &m.Code)
		default:
			n, err = pb.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(pb.ErrParse))
		}
		b = b[n:]
	}
	return pb.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Status) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Status) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Status) MarshalJSONTo(e *jsontext.Encoder) error {
	return pb.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Status) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.Message) > 0 {
		b, err = pb.Quote(append(b, ",\"message\":"...), m.Message, err)
	}
	if m.Code != 0 {
		b = strconv.AppendInt(append(b, ",\"code\":"...), int64(m.Code), 10)
	}
	return pb.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Status) UnmarshalJSON(b []byte) error { *m = Status{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Status) ProtoMergeJSON(b []byte) error {
	return pb.MergeJSON(b, "opentelemetry.proto.trace.v1.Status", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Status) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Status{}
	return pb.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Status) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [2]bool
	for kt, err := pb.OpenObject(d, "opentelemetry.proto.trace.v1.Status"); kt.Kind() != jsontext.KindEndObject; kt, err = pb.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "message":
			err = pb.Field(d, &seen[0], key, "opentelemetry.proto.trace.v1.Status", &m.Message, pb.JSONString)
		case "code":
			err = pb.Field(d, &seen[1], key, "opentelemetry.proto.trace.v1.Status", &m.Code, traceJStatusStatusCode)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

func traceJStatusStatusCode(d *jsontext.Decoder, p *Status_StatusCode, name string) error {
	return pb.JSONEnum(d, p, Status_StatusCode_value, name, "opentelemetry.proto.trace.v1.Status.StatusCode", false)
}

var (
	traceZTracesData    TracesData
	traceZResourceSpans ResourceSpans
	traceZScopeSpans    ScopeSpans
	traceZSpan          Span
	traceZSpan_Event    Span_Event
	traceZSpan_Link     Span_Link
	traceZStatus        Status
)
